// PopulationCell — per-chunk ecosystem population density.
//
// Ported from src/core/simulation/population_cell.hpp.
// Namespace: science_and_theology -> snt::game.

#pragma once

#include <algorithm>
#include <cstdint>

namespace snt::game {

// ============================================================
// EcosystemBiome — biome type constants for PopulationCell
// ============================================================
//
// Determines which species spawn in a chunk and which
// BiomeOverride parameters apply. Inferred from surface
// terrain material composition by EcosystemSystem.
//
// Values must fit in uint8_t (PopulationCell::biome_type).

namespace ecosystem_biome {
    constexpr uint8_t kPlains  = 0;  // Default: dirt/grass surface
    constexpr uint8_t kDesert  = 1;  // Sand-dominated surface
    constexpr uint8_t kRocky   = 2;  // Stone-dominated surface
    constexpr uint8_t kOcean   = 3;  // Water-dominated surface
    constexpr uint8_t kBarren  = 4;  // Toxic/corrosive atmosphere
    constexpr uint8_t kCount   = 5;
} // namespace ecosystem_biome

// ============================================================
// PopulationCell — per-chunk ecosystem population density
// ============================================================
//
// Stores aggregate population densities for a single chunk.
// Lightweight data structure used by EcosystemSystem
// for Lotka-Volterra-style population dynamics.
//
// All density values are in [0, 1] range where:
//   0.0 = completely absent
//   1.0 = maximum carrying capacity
//
// Hunting pressure fields (hunting_pressure_herb/pred) are
// additional death terms injected by player kills. They
// accumulate on each kill and decay naturally each tick,
// providing a smooth and ecologically sound feedback loop
// instead of directly mutating density values.
//
// PopulationCell is owned directly by the matching GameChunkSidecar. The
// ecosystem system mutates that durable value in place, so world persistence
// never needs a legacy runtime-map synchronization pass.

struct PopulationCell {
    // Ground vegetation cover [0, 1].
    // Influenced by soil fertility, water, season, and herbivore grazing.
    float vegetation_density = 0.5f;

    // Herbivore (prey) population density [0, 1].
    // Influenced by vegetation availability and predator pressure.
    float herbivore_density = 0.3f;

    // Predator population density [0, 1].
    // Influenced by herbivore availability.
    float predator_density = 0.1f;

    // Soil nutrient level [0, 1].
    // Increased by decomposition of dead biomass.
    float soil_fertility = 0.5f;

    // Water availability for vegetation [0, 1].
    // Determined by biome base value and seasonal modifier.
    float water_availability = 0.5f;

    // Decomposing organic matter [0, 1].
    // Generated by animal death and vegetation decay;
    // consumed by decomposition into soil fertility.
    float dead_biomass = 0.0f;

    // --- Hunting pressure (player kill feedback) ---

    // Accumulated hunting pressure on herbivores [0, +inf).
    // Increased by each player kill of a herbivore proxy.
    // Decays naturally each tick (multiplied by decay_rate).
    // Acts as an extra death term in the Lotka-Volterra equation:
    //   dH/dt = ... - hunting_pressure_herb * H
    float hunting_pressure_herb = 0.0f;

    // Accumulated hunting pressure on predators [0, +inf).
    // Same semantics as hunting_pressure_herb for predator dynamics:
    //   dP/dt = ... - hunting_pressure_pred * P
    float hunting_pressure_pred = 0.0f;

    // Biome type index for parameter lookup in EcosystemParams.
    uint8_t biome_type = 0;

    // Authoritative tick at which this cell last received a macro ecosystem
    // integration step. Cells outside every player ecology circle do not
    // advance every fixed tick; when one becomes relevant again the
    // ecosystem uses this durable marker for a bounded deterministic catch-up.
    // Zero means the cell has not yet been activated by the current runtime.
    uint64_t last_macro_simulation_tick = 0;

    // Clamp all density values to [0, 1].
    void clamp_all() {
        vegetation_density = std::clamp(vegetation_density, 0.0f, 1.0f);
        herbivore_density = std::clamp(herbivore_density, 0.0f, 1.0f);
        predator_density = std::clamp(predator_density, 0.0f, 1.0f);
        soil_fertility = std::clamp(soil_fertility, 0.0f, 1.0f);
        water_availability = std::clamp(water_availability, 0.0f, 1.0f);
        dead_biomass = std::clamp(dead_biomass, 0.0f, 1.0f);
    }
};

} // namespace snt::game
