// Generated by tools/migrate_legacy_terrain_material_catalog.ps1 from the retired Godot catalog.
// This file is game-owned static content; it is not loaded through Godot at runtime.

#define SNT_LOG_CHANNEL "game.worldgen_catalog"
#include "game/worldgen/legacy_terrain_material_catalog.h"

#include "core/log.h"
#include "game/worldgen/world_gen_config.h"

#include <utility>

namespace snt::game {
namespace {

void add_material(WorldGenConfigSnapshot& config, TerrainMaterialDef material) {
    config.materials.push_back(std::move(material));
}

}  // namespace

void register_migrated_legacy_terrain_material_catalog(WorldGenConfigSnapshot& config) {
    config.materials.reserve(config.materials.size() + 152);
    add_material(config, {
        .key = "snt:acacia_leaves",
        .title_key = "terrain.acacia_leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.15f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:acacia_sapling",
        .title_key = "terrain.acacia_sapling",
        .flags = TF_MINEABLE,
        .hardness = 0.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "sapling.acacia", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:acacia_wood",
        .title_key = "terrain.acacia_wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 0.9f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "log.acacia", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:air",
        .title_key = "terrain.air",
        .flags = 0u,
        .hardness = 0.0f,
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:anorthosite_rock",
        .title_key = "terrain.anorthosite",
        .flags = TF_SOLID | TF_MINEABLE | TF_COLLAPSE_RISK,
        .hardness = 1.4f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.anorthosite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .collapse_chance = 0.2f,
        .rock_layer_key = "snt:anorthosite",
    });
    add_material(config, {
        .key = "snt:anvil",
        .title_key = "terrain.anvil",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
    });
    add_material(config, {
        .key = "snt:basalt_rock",
        .title_key = "terrain.basalt",
        .flags = TF_SOLID | TF_MINEABLE | TF_COLLAPSE_RISK,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.basalt", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .collapse_chance = 0.25f,
        .rock_layer_key = "snt:basalt",
    });
    add_material(config, {
        .key = "snt:birch_leaves",
        .title_key = "terrain.birch_leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.15f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:birch_sapling",
        .title_key = "terrain.birch_sapling",
        .flags = TF_MINEABLE,
        .hardness = 0.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "sapling.birch", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:birch_wood",
        .title_key = "terrain.birch_wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 0.8f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "log.birch", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:bloomery",
        .title_key = "terrain.bloomery",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "refractory_brick", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:carrot_growing",
        .title_key = "terrain.carrot_growing",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.carrot", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:carrot_mature",
        .title_key = "terrain.carrot_mature",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crop.carrot", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
            {.item_key = "seed.carrot", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:carrot_seed",
        .title_key = "terrain.carrot_seed",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.carrot", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:carrot_sprout",
        .title_key = "terrain.carrot_sprout",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.carrot", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:charcoal",
        .title_key = "terrain.charcoal",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 0.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "charcoal", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:cherry_leaves",
        .title_key = "terrain.cherry_leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.15f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:cherry_sapling",
        .title_key = "terrain.cherry_sapling",
        .flags = TF_MINEABLE,
        .hardness = 0.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "sapling.cherry", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:cherry_wood",
        .title_key = "terrain.cherry_wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 0.7f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "log.cherry", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:clay",
        .title_key = "terrain.clay",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.4f,
        .required_tool_tag = "shovel",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "clay_ball", .count = 1, .min_count = 1, .max_count = 3, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:core_barrier",
        .title_key = "terrain.core_barrier",
        .flags = TF_SOLID | TF_INDESTRUCTIBLE,
        .hardness = -1.0f,
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:cotton_growing",
        .title_key = "terrain.cotton_growing",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.cotton", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:cotton_mature",
        .title_key = "terrain.cotton_mature",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crop.cotton", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
            {.item_key = "seed.cotton", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:cotton_seed",
        .title_key = "terrain.cotton_seed",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.cotton", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:cotton_sprout",
        .title_key = "terrain.cotton_sprout",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.cotton", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:deepstone",
        .title_key = "terrain.deepstone",
        .flags = TF_SOLID | TF_MINEABLE | TF_COLLAPSE_RISK,
        .hardness = 10.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "dust.stone", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .collapse_chance = 0.5f,
        .rock_layer_key = "snt:deeprock",
    });
    add_material(config, {
        .key = "snt:dirt",
        .title_key = "terrain.dirt",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.5f,
        .required_tool_tag = "shovel",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "tiny_dust.stone", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:farmland",
        .title_key = "terrain.farmland",
        .flags = TF_SOLID | TF_MINEABLE | TF_WALKABLE,
        .hardness = 0.5f,
        .required_tool_tag = "shovel",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:fence",
        .title_key = "terrain.fence",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "fence", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:granite_rock",
        .title_key = "terrain.granite",
        .flags = TF_SOLID | TF_MINEABLE | TF_COLLAPSE_RISK,
        .hardness = 1.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.granite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .rock_layer_key = "snt:granite",
    });
    add_material(config, {
        .key = "snt:herb_growing",
        .title_key = "terrain.herb_growing",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.herb", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:herb_mature",
        .title_key = "terrain.herb_mature",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crop.herb", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
            {.item_key = "seed.herb", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:herb_seed",
        .title_key = "terrain.herb_seed",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.herb", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:herb_sprout",
        .title_key = "terrain.herb_sprout",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.herb", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ice",
        .title_key = "terrain.ice",
        .flags = TF_SOLID | TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.6f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:komatiite_rock",
        .title_key = "terrain.komatiite",
        .flags = TF_SOLID | TF_MINEABLE | TF_COLLAPSE_RISK,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "dust.komatiite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .collapse_chance = 0.35f,
        .rock_layer_key = "snt:komatiite",
    });
    add_material(config, {
        .key = "snt:ladder",
        .title_key = "terrain.ladder",
        .flags = TF_MINEABLE | TF_CLIMBABLE,
        .hardness = 0.5f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "ladder", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:lava",
        .title_key = "terrain.lava",
        .flags = TF_LIQUID,
        .hardness = 100.0f,
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:leaves",
        .title_key = "terrain.leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.2f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:log_pile",
        .title_key = "terrain.log_pile",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 0.6f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:maple_leaves",
        .title_key = "terrain.maple_leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.2f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:maple_sapling",
        .title_key = "terrain.maple_sapling",
        .flags = TF_MINEABLE,
        .hardness = 0.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "sapling.maple", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:maple_wood",
        .title_key = "terrain.maple_wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "log.maple", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:marble_rock",
        .title_key = "terrain.marble",
        .flags = TF_SOLID | TF_MINEABLE | TF_COLLAPSE_RISK,
        .hardness = 1.3f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.marble", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .collapse_chance = 0.2f,
        .rock_layer_key = "snt:marble",
    });
    add_material(config, {
        .key = "snt:oak_leaves",
        .title_key = "terrain.oak_leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.2f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:oak_sapling",
        .title_key = "terrain.oak_sapling",
        .flags = TF_MINEABLE,
        .hardness = 0.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "sapling.oak", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:oak_wood",
        .title_key = "terrain.oak_wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "log.oak", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:olive_leaves",
        .title_key = "terrain.olive_leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.2f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:olive_sapling",
        .title_key = "terrain.olive_sapling",
        .flags = TF_MINEABLE,
        .hardness = 0.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "sapling.olive", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:olive_wood",
        .title_key = "terrain.olive_wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.1f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "log.olive", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_antimony",
        .title_key = "terrain.antimony_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.stibnite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_arsenic",
        .title_key = "terrain.arsenic_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.arsenopyrite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_barium",
        .title_key = "terrain.barium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.barite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_bauxite",
        .title_key = "terrain.bauxite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.bauxite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_beryllium",
        .title_key = "terrain.beryllium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.bertrandite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_bismuth",
        .title_key = "terrain.bismuth_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.bismuthinite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_boron",
        .title_key = "terrain.boron_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.kernite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_bromine",
        .title_key = "terrain.bromine_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.2f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.bromargyrite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_cadmium",
        .title_key = "terrain.cadmium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.greenockite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_calcium",
        .title_key = "terrain.calcium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crushed.calcite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_cassiterite",
        .title_key = "terrain.cassiterite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.cassiterite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_cesium",
        .title_key = "terrain.cesium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.pollucite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_chalcopyrite",
        .title_key = "terrain.chalcopyrite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.2f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.chalcopyrite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_chromium",
        .title_key = "terrain.chromium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.chromite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_cinnabar",
        .title_key = "terrain.cinnabar_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.cinnabar", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_coal",
        .title_key = "terrain.coal_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "gem.coal", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_cobalt",
        .title_key = "terrain.cobalt_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.cobaltite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_copper",
        .title_key = "terrain.copper_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.malachite", .count = 1, .min_count = 1, .max_count = 2, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_diamond",
        .title_key = "terrain.diamond_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 5.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "gem.diamond", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_emerald",
        .title_key = "terrain.emerald_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "gem.emerald", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_fluorite",
        .title_key = "terrain.fluorite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.fluorite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_galena",
        .title_key = "terrain.galena_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.3f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.galena", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_gallium",
        .title_key = "terrain.gallium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.gallite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_germanium",
        .title_key = "terrain.germanium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.germanite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_gold",
        .title_key = "terrain.gold_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.gold", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_graphite",
        .title_key = "terrain.graphite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "dust.graphite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_hafnium",
        .title_key = "terrain.hafnium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.baddeleyite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_ilmenite",
        .title_key = "terrain.ilmenite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.ilmenite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_indium",
        .title_key = "terrain.indium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.roquesite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_iodine",
        .title_key = "terrain.iodine_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.2f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crushed.iodargyrite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_iridium",
        .title_key = "terrain.iridium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 5.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.iridium_oxide", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_iron",
        .title_key = "terrain.iron_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.hematite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_lead",
        .title_key = "terrain.lead_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.2f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.galena", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_lithium",
        .title_key = "terrain.lithium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.spodumene", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_magnesium",
        .title_key = "terrain.magnesium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.magnesite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_magnetite",
        .title_key = "terrain.magnetite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.magnetite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_manganese",
        .title_key = "terrain.manganese_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.pyrolusite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_molybdenum",
        .title_key = "terrain.molybdenum_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.molybdenite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_nickel",
        .title_key = "terrain.nickel_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.pentlandite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_niobium",
        .title_key = "terrain.niobium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.columbite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_osmium",
        .title_key = "terrain.osmium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 5.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.osmiridium", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_palladium",
        .title_key = "terrain.palladium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.stibiopalladinite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_pentlandite",
        .title_key = "terrain.pentlandite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.pentlandite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_phosphorus",
        .title_key = "terrain.phosphorus_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.apatite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_platinum",
        .title_key = "terrain.platinum_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 5.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.sperrylite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_potassium",
        .title_key = "terrain.potassium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.2f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crushed.sylvite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_pyrite",
        .title_key = "terrain.pyrite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.pyrite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_rare_earth",
        .title_key = "terrain.rare_earth_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.monazite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_rhenium",
        .title_key = "terrain.rhenium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.rheniite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_rhodium",
        .title_key = "terrain.rhodium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.rhodium_oxide", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_rubidium",
        .title_key = "terrain.rubidium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.lepidolite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_ruby",
        .title_key = "terrain.ruby_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "gem.ruby", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_ruthenium",
        .title_key = "terrain.ruthenium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.laurite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_salt",
        .title_key = "terrain.salt_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.2f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "dust.salt", .count = 1, .min_count = 1, .max_count = 3, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_sapphire",
        .title_key = "terrain.sapphire_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "gem.sapphire", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_scandium",
        .title_key = "terrain.scandium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.thortveitite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_selenium",
        .title_key = "terrain.selenium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.clausthalite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_silver",
        .title_key = "terrain.silver_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.silver", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_sphalerite",
        .title_key = "terrain.sphalerite_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.sphalerite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_strontium",
        .title_key = "terrain.strontium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.celestine", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_sulfur",
        .title_key = "terrain.sulfur_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.sulfur", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_tantalum",
        .title_key = "terrain.tantalum_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.tantalite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_tellurium",
        .title_key = "terrain.tellurium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.calaverite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_thallium",
        .title_key = "terrain.thallium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.crookesite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_thorium",
        .title_key = "terrain.thorium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.thorite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_tin",
        .title_key = "terrain.tin_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.cassiterite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_titanium",
        .title_key = "terrain.titanium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.rutile", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_tungsten",
        .title_key = "terrain.tungsten_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 4.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.wolframite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_uranium",
        .title_key = "terrain.uranium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 5.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 3,
        .drops = {
            {.item_key = "crushed.uraninite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_vanadium",
        .title_key = "terrain.vanadium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.patronite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_yttrium",
        .title_key = "terrain.yttrium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.xenotime", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_zinc",
        .title_key = "terrain.zinc_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 2.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "crushed.sphalerite", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:ore_zirconium",
        .title_key = "terrain.zirconium_ore",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 3.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 2,
        .drops = {
            {.item_key = "crushed.zircon", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:pit_kiln",
        .title_key = "terrain.pit_kiln",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 0.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:potato_growing",
        .title_key = "terrain.potato_growing",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.potato", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:potato_mature",
        .title_key = "terrain.potato_mature",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crop.potato", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
            {.item_key = "seed.potato", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:potato_seed",
        .title_key = "terrain.potato_seed",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.potato", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:potato_sprout",
        .title_key = "terrain.potato_sprout",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.potato", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:pumpkin_growing",
        .title_key = "terrain.pumpkin_growing",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.pumpkin", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:pumpkin_mature",
        .title_key = "terrain.pumpkin_mature",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crop.pumpkin", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
            {.item_key = "seed.pumpkin", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:pumpkin_seed",
        .title_key = "terrain.pumpkin_seed",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.pumpkin", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:pumpkin_sprout",
        .title_key = "terrain.pumpkin_sprout",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.pumpkin", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:regolith_rock",
        .title_key = "terrain.regolith",
        .flags = TF_SOLID | TF_MINEABLE | TF_GRAVITY_FALL,
        .hardness = 0.6f,
        .required_tool_tag = "shovel",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "dust.regolith", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .collapse_chance = 0.1f,
        .rock_layer_key = "snt:regolith",
    });
    add_material(config, {
        .key = "snt:sand",
        .title_key = "terrain.sand",
        .flags = TF_WALKABLE | TF_MINEABLE | TF_GRAVITY_FALL,
        .hardness = 0.45f,
        .required_tool_tag = "shovel",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "tiny_dust.stone", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:sandstone_rock",
        .title_key = "terrain.sandstone",
        .flags = TF_SOLID | TF_MINEABLE | TF_GRAVITY_FALL,
        .hardness = 0.8f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "dust.sandstone", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .collapse_chance = 0.15f,
        .rock_layer_key = "snt:sandstone",
    });
    add_material(config, {
        .key = "snt:sequoia_leaves",
        .title_key = "terrain.sequoia_leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.2f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:sequoia_sapling",
        .title_key = "terrain.sequoia_sapling",
        .flags = TF_MINEABLE,
        .hardness = 0.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "sapling.sequoia", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:sequoia_wood",
        .title_key = "terrain.sequoia_wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.2f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "log.sequoia", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:shale_rock",
        .title_key = "terrain.shale",
        .flags = TF_SOLID | TF_MINEABLE | TF_COLLAPSE_RISK,
        .hardness = 1.0f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.shale", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .collapse_chance = 0.4f,
        .rock_layer_key = "snt:shale",
    });
    add_material(config, {
        .key = "snt:snow",
        .title_key = "terrain.snow",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.2f,
        .required_tool_tag = "shovel",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:spruce_leaves",
        .title_key = "terrain.spruce_leaves",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.2f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:spruce_sapling",
        .title_key = "terrain.spruce_sapling",
        .flags = TF_MINEABLE,
        .hardness = 0.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "sapling.spruce", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:spruce_wood",
        .title_key = "terrain.spruce_wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "log.spruce", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:stone",
        .title_key = "terrain.stone",
        .flags = TF_SOLID | TF_MINEABLE | TF_COLLAPSE_RISK,
        .hardness = 1.5f,
        .required_tool_tag = "pickaxe",
        .required_mining_level = 1,
        .drops = {
            {.item_key = "dust.stone", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
        .rock_layer_key = "snt:granite",
    });
    add_material(config, {
        .key = "snt:straw",
        .title_key = "terrain.straw",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.1f,
        .required_tool_tag = "hoe",
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:water",
        .title_key = "terrain.water",
        .flags = TF_LIQUID,
        .hardness = 100.0f,
        .required_mining_level = 0,
    });
    add_material(config, {
        .key = "snt:wheat_growing",
        .title_key = "terrain.wheat_growing",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.wheat", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:wheat_mature",
        .title_key = "terrain.wheat_mature",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "crop.wheat", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
            {.item_key = "seed.wheat", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:wheat_seed",
        .title_key = "terrain.wheat_seed",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.wheat", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:wheat_sprout",
        .title_key = "terrain.wheat_sprout",
        .flags = TF_WALKABLE | TF_MINEABLE,
        .hardness = 0.0f,
        .required_mining_level = 0,
        .drops = {
            {.item_key = "seed.wheat", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:wood",
        .title_key = "terrain.wood",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "dust.wood", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });
    add_material(config, {
        .key = "snt:workbench",
        .title_key = "terrain.workbench",
        .flags = TF_SOLID | TF_MINEABLE,
        .hardness = 1.0f,
        .required_tool_tag = "axe",
        .required_mining_level = 0,
        .drops = {
            {.item_key = "workbench", .count = 1, .min_count = 1, .max_count = 1, .chance = 1.0f},
        },
    });

    SNT_LOG_INFO("Registered migrated terrain material catalog: %zu semantic definitions",
                 config.materials.size());
}

}  // namespace snt::game
