#pragma once

#include <cstdint>
#include <string>
#include <functional>
#include <vector>

#include "terrain_data.hpp"
#include "entity_data.hpp"

namespace science_and_theology {

// Lifecycle state of a chunk in the streaming system.
enum class ChunkState : uint8_t {
    UNLOADED   = 0,
    GENERATING = 1,
    GENERATED  = 2,
    ACTIVE     = 3,
    SLEEPING   = 4,
};

// Display name for each chunk state.
constexpr const char* kChunkStateNames[] = {
    "Unloaded", "Generating", "Generated", "Active", "Sleeping",
};

// Identifies a unique chunk in the world across all layers.
struct ChunkKey {
    std::string layer_id;
    int chunk_x = 0;
    int chunk_y = 0;

    bool operator==(const ChunkKey& other) const {
        return chunk_x == other.chunk_x
            && chunk_y == other.chunk_y
            && layer_id == other.layer_id;
    }

    bool operator!=(const ChunkKey& other) const {
        return !(*this == other);
    }
};

// Placement data for a generated connector between two layers.
// Mirrors MapConnector.gd on the Godot side.
struct ConnectorPlacement {
    std::string connector_id;
    std::string from_layer;
    int from_cell_x = 0;
    int from_cell_y = 0;
    std::string to_layer;
    int to_cell_x = 0;
    int to_cell_y = 0;
    bool one_way = false;
    bool locked = false;
    std::string connector_type;       // "cave_entrance", "rift", "ruin_gate"
    int activation_mode = 0;           // 0 = INTERACT, 1 = AUTO_ON_ENTER
};

// World data shard. One chunk represents a fixed-size region of the world.
// This is a pure data container, not a Godot node.
struct ChunkData {
    // Chunk size in cells. Must match the global ChunkConfig.
    static constexpr int kChunkSize = 32;

    int chunk_x = 0;
    int chunk_y = 0;
    ChunkState state = ChunkState::UNLOADED;

    TerrainData terrain;

    // Connector placements generated by pass_gameplay.
    // Persisted to GDScript for ConnectorManager instantiation.
    std::vector<ConnectorPlacement> connectors;

    // Entity and machine reference IDs owned by this chunk.
    // Full runtime data lives in the global entity/machine registries.
    std::vector<EntityId> entities;
    std::vector<MachineId> machines;

    // Connector runtime IDs (set after ConnectorManager instantiation).
    std::vector<ConnectorId> connector_ids;
};

} // namespace science_and_theology

// std::hash specialization for ChunkKey to use in unordered_map.
template <>
struct std::hash<science_and_theology::ChunkKey> {
    size_t operator()(const science_and_theology::ChunkKey& key) const {
        size_t h = std::hash<std::string>()(key.layer_id);
        h ^= std::hash<int>()(key.chunk_x) + 0x9e3779b9 + (h << 6) + (h >> 2);
        h ^= std::hash<int>()(key.chunk_y) + 0x9e3779b9 + (h << 6) + (h >> 2);
        return h;
    }
};