// Game-owned AngelScript material content. The immutable standard periodic
// table is registered by C++ before this script; this catalog owns compounds,
// alloys, non-element forms, and fictional materials.

// Keep these bit values aligned with GameMaterialGenerationFlag in C++.
const int kGenerationDust = 1;
const int kGenerationMetal = 2;
const int kGenerationGem = 4;
const int kGenerationOre = 8;
const int kGenerationCell = 16;
const int kGenerationPlasma = 32;
const int kGenerationWire = 64;
const int kGenerationBlock = 128;
const int kGenerationPlate = 256;
const int kGenerationRod = 512;

const int kGenerationCellPlasma = kGenerationCell | kGenerationPlasma;
const int kGenerationDustBlock = kGenerationDust | kGenerationBlock;
const int kGenerationDustGemBlock =
    kGenerationDust | kGenerationGem | kGenerationBlock;
const int kGenerationDustMetalWireBlock =
    kGenerationDust | kGenerationMetal | kGenerationWire | kGenerationBlock;
const int kGenerationDustBlockPlate =
    kGenerationDust | kGenerationBlock | kGenerationPlate;
const int kGenerationDustBlockPlateRod =
    kGenerationDust | kGenerationBlock | kGenerationPlate | kGenerationRod;

void snt_register() {
    snt_register_material("stone", "material.stone", kGenerationDust, 0, 8421504, 0, 0, 1.0f, "?");
    snt_register_material("flint", "material.flint", kGenerationDust, 0, 3158064, 0, 0, 1.0f, "SiO2");
    snt_register_material("coal", "material.coal", kGenerationDustGemBlock, 0, 1710618, 0, 0, 1.0f, "C");
    snt_register_material("charcoal", "material.charcoal", kGenerationDust, 0, 2759178, 0, 0, 1.0f, "C");
    snt_register_material("lignite", "material.lignite", kGenerationDust, 0, 3811866, 0, 0, 1.0f, "C");
    snt_register_material("bronze", "material.bronze", kGenerationDustMetalWireBlock, 0, 13467442, 0, 0, 0.0f, "Cu+Sn");
    snt_add_material_element("bronze", "Cu", 3);
    snt_add_material_element("bronze", "Sn", 1);
    snt_register_material("brass", "material.brass", kGenerationDustMetalWireBlock, 0, 12952898, 0, 0, 0.0f, "Cu+Zn");
    snt_add_material_element("brass", "Cu", 3);
    snt_add_material_element("brass", "Zn", 1);
    snt_register_material("steel", "material.steel", kGenerationDustMetalWireBlock, 0, 8421520, 0, 0, 0.0f, "Fe+C");
    snt_add_material_element("steel", "Fe", 1);
    snt_add_material_element("steel", "C", 1);
    snt_register_material("stainless_steel", "material.stainless_steel", kGenerationDustMetalWireBlock, 0, 12632256, 0, 0, 0.0f, "Fe+Cr+Ni+Mn");
    snt_add_material_element("stainless_steel", "Fe", 9);
    snt_add_material_element("stainless_steel", "Cr", 1);
    snt_add_material_element("stainless_steel", "Ni", 1);
    snt_add_material_element("stainless_steel", "Mn", 1);
    snt_register_material("electrum", "material.electrum", kGenerationDustMetalWireBlock, 0, 14337167, 0, 0, 0.0f, "Au+Ag");
    snt_add_material_element("electrum", "Au", 1);
    snt_add_material_element("electrum", "Ag", 1);
    snt_register_material("invar", "material.invar", kGenerationDustMetalWireBlock, 0, 10526864, 0, 0, 0.0f, "Fe+Ni");
    snt_add_material_element("invar", "Fe", 2);
    snt_add_material_element("invar", "Ni", 1);
    snt_register_material("cupronickel", "material.cupronickel", kGenerationDustMetalWireBlock, 0, 12623984, 0, 0, 0.0f, "Cu+Ni");
    snt_add_material_element("cupronickel", "Cu", 1);
    snt_add_material_element("cupronickel", "Ni", 1);
    snt_register_material("solder", "material.solder", kGenerationDustMetalWireBlock, 0, 9474192, 0, 0, 0.0f, "Sn+Pb");
    snt_add_material_element("solder", "Sn", 9);
    snt_add_material_element("solder", "Pb", 1);
    snt_register_material("tin_alloy", "material.tin_alloy", kGenerationDustMetalWireBlock, 0, 12632256, 0, 0, 0.0f, "Sn+Fe");
    snt_add_material_element("tin_alloy", "Sn", 1);
    snt_add_material_element("tin_alloy", "Fe", 1);
    snt_register_material("red_alloy", "material.red_alloy", kGenerationDustMetalWireBlock, 0, 16728128, 0, 0, 0.0f, "?");
    snt_register_material("annealed_copper", "material.annealed_copper", kGenerationDustMetalWireBlock, 0, 16756832, 0, 0, 0.0f, "Cu");
    snt_add_material_element("annealed_copper", "Cu", 1);
    snt_register_material("tungstensteel", "material.tungstensteel", kGenerationDustMetalWireBlock, 0, 8421536, 0, 0, 0.0f, "W+Fe");
    snt_add_material_element("tungstensteel", "W", 1);
    snt_add_material_element("tungstensteel", "Fe", 1);
    snt_register_material("hss_g", "material.hss_g", kGenerationDustMetalWireBlock, 0, 10526896, 0, 0, 0.0f, "?");
    snt_register_material("naquadah", "material.naquadah", kGenerationDustMetalWireBlock, 0, 4235328, 0, 0, 0.0f, "?");
    snt_register_material("naquadah_alloy", "material.naquadah_alloy", kGenerationDustMetalWireBlock, 0, 6340704, 0, 0, 0.0f, "?");
    snt_register_material("magnalium", "material.magnalium", kGenerationDustMetalWireBlock, 0, 12636352, 0, 0, 0.0f, "Mg+Al");
    snt_add_material_element("magnalium", "Mg", 2);
    snt_add_material_element("magnalium", "Al", 1);
    snt_register_material("duralumin", "material.duralumin", kGenerationDustMetalWireBlock, 0, 12634320, 0, 0, 0.0f, "Al+Cu+Mg");
    snt_add_material_element("duralumin", "Al", 93);
    snt_add_material_element("duralumin", "Cu", 4);
    snt_add_material_element("duralumin", "Mg", 2);
    snt_register_material("alnico", "material.alnico", kGenerationDustMetalWireBlock, 0, 9470096, 0, 0, 0.0f, "Al+Ni+Co+Fe");
    snt_add_material_element("alnico", "Al", 1);
    snt_add_material_element("alnico", "Ni", 2);
    snt_add_material_element("alnico", "Co", 1);
    snt_add_material_element("alnico", "Fe", 5);
    snt_register_material("nichrome", "material.nichrome", kGenerationDustMetalWireBlock, 0, 10526896, 0, 0, 0.0f, "Ni+Cr");
    snt_add_material_element("nichrome", "Ni", 4);
    snt_add_material_element("nichrome", "Cr", 1);
    snt_register_material("monel", "material.monel", kGenerationDustMetalWireBlock, 0, 9478288, 0, 0, 0.0f, "Ni+Cu+Fe");
    snt_add_material_element("monel", "Ni", 6);
    snt_add_material_element("monel", "Cu", 3);
    snt_add_material_element("monel", "Fe", 1);
    snt_register_material("kovar", "material.kovar", kGenerationDustMetalWireBlock, 0, 10526880, 0, 0, 0.0f, "Fe+Ni+Co");
    snt_add_material_element("kovar", "Fe", 5);
    snt_add_material_element("kovar", "Ni", 3);
    snt_add_material_element("kovar", "Co", 1);
    snt_register_material("inconel", "material.inconel", kGenerationDustMetalWireBlock, 0, 9474208, 0, 0, 0.0f, "Ni+Cr+Fe");
    snt_add_material_element("inconel", "Ni", 7);
    snt_add_material_element("inconel", "Cr", 2);
    snt_add_material_element("inconel", "Fe", 1);
    snt_register_material("phosphor_bronze", "material.phosphor_bronze", kGenerationDustMetalWireBlock, 0, 12615744, 0, 0, 0.0f, "Cu+Sn+P");
    snt_add_material_element("phosphor_bronze", "Cu", 10);
    snt_add_material_element("phosphor_bronze", "Sn", 1);
    snt_add_material_element("phosphor_bronze", "P", 1);
    snt_register_material("beryllium_copper", "material.beryllium_copper", kGenerationDustMetalWireBlock, 0, 13676672, 0, 0, 0.0f, "Cu+Be");
    snt_add_material_element("beryllium_copper", "Cu", 49);
    snt_add_material_element("beryllium_copper", "Be", 1);
    snt_register_material("titanium_alloy", "material.titanium_alloy", kGenerationDustMetalWireBlock, 0, 10526896, 0, 0, 0.0f, "Ti+Al+V");
    snt_add_material_element("titanium_alloy", "Ti", 44);
    snt_add_material_element("titanium_alloy", "Al", 3);
    snt_add_material_element("titanium_alloy", "V", 3);
    snt_register_material("nitinol", "material.nitinol", kGenerationDustMetalWireBlock, 0, 9474192, 0, 0, 0.0f, "Ni+Ti");
    snt_add_material_element("nitinol", "Ni", 1);
    snt_add_material_element("nitinol", "Ti", 1);
    snt_register_material("permalloy", "material.permalloy", kGenerationDustMetalWireBlock, 0, 10526896, 0, 0, 0.0f, "Ni+Fe");
    snt_add_material_element("permalloy", "Ni", 4);
    snt_add_material_element("permalloy", "Fe", 1);
    snt_register_material("rose_metal", "material.rose_metal", kGenerationDustMetalWireBlock, 0, 12624000, 0, 0, 0.0f, "Bi+Pb+Sn");
    snt_add_material_element("rose_metal", "Bi", 2);
    snt_add_material_element("rose_metal", "Pb", 1);
    snt_add_material_element("rose_metal", "Sn", 1);
    snt_register_material("woods_metal", "material.woods_metal", kGenerationDustMetalWireBlock, 0, 12624032, 0, 0, 0.0f, "Bi+Pb+Sn+Cd");
    snt_add_material_element("woods_metal", "Bi", 2);
    snt_add_material_element("woods_metal", "Pb", 1);
    snt_add_material_element("woods_metal", "Sn", 1);
    snt_add_material_element("woods_metal", "Cd", 1);
    snt_register_material("diamond", "material.diamond", kGenerationDustGemBlock, 0, 8446176, 0, 0, 0.0f, "C");
    snt_register_material("ruby", "material.ruby", kGenerationDustGemBlock, 0, 14688288, 0, 0, 0.0f, "Al2O3+Cr");
    snt_register_material("sapphire", "material.sapphire", kGenerationDustGemBlock, 0, 2113760, 0, 0, 0.0f, "Al2O3");
    snt_register_material("emerald", "material.emerald", kGenerationDustGemBlock, 0, 2154528, 0, 0, 0.0f, "Be3Al2Si6O18");
    snt_register_material("amethyst", "material.amethyst", kGenerationDustGemBlock, 0, 8397024, 0, 0, 0.0f, "SiO2");
    snt_register_material("lapis", "material.lapis", kGenerationDustGemBlock, 0, 2113728, 0, 0, 0.0f, "Na8Al6Si6O24S2");
    snt_register_material("quartz", "material.quartz", kGenerationDustGemBlock, 0, 14737648, 0, 0, 0.0f, "SiO2");
    snt_register_material("nether_quartz", "material.nether_quartz", kGenerationDustGemBlock, 0, 15786208, 0, 0, 0.0f, "SiO2");
    snt_register_material("graphene", "material.graphene", kGenerationDust, 0, 2105392, 0, 0, 0.0f, "C");
    snt_register_material("superconductor", "material.superconductor", kGenerationDustMetalWireBlock, 0, 8405216, 0, 0, 0.0f, "?");
    snt_register_material("water", "material.water", kGenerationCell, 1, 4227327, 273, 373, 18.0f, "H2O");
    snt_add_material_element("water", "H", 2);
    snt_add_material_element("water", "O", 1);
    snt_register_material("lava", "material.lava", kGenerationCell, 1, 16728064, 0, 0, 0.0f, "?");
    snt_register_material("steam", "material.steam", kGenerationCell, 2, 12632256, 373, 373, 18.0f, "H2O");
    snt_add_material_element("steam", "H", 2);
    snt_add_material_element("steam", "O", 1);
    snt_register_material("creosote", "material.creosote", kGenerationCell, 1, 6044190, 0, 0, 0.0f, "?");
    snt_register_material("sulfuric_acid", "material.sulfuric_acid", kGenerationCell, 1, 13158400, 0, 0, 98.1f, "H2SO4");
    snt_add_material_element("sulfuric_acid", "H", 2);
    snt_add_material_element("sulfuric_acid", "S", 1);
    snt_add_material_element("sulfuric_acid", "O", 4);
    snt_register_material("hydrochloric_acid", "material.hydrochloric_acid", kGenerationCell, 1, 12648384, 0, 0, 36.5f, "HCl");
    snt_add_material_element("hydrochloric_acid", "H", 1);
    snt_add_material_element("hydrochloric_acid", "Cl", 1);
    snt_register_material("nitric_acid", "material.nitric_acid", kGenerationCell, 1, 16760896, 0, 0, 63.0f, "HNO3");
    snt_add_material_element("nitric_acid", "H", 1);
    snt_add_material_element("nitric_acid", "N", 1);
    snt_add_material_element("nitric_acid", "O", 3);
    snt_register_material("hydrofluoric_acid", "material.hydrofluoric_acid", kGenerationCell, 1, 8454016, 0, 0, 20.0f, "HF");
    snt_add_material_element("hydrofluoric_acid", "H", 1);
    snt_add_material_element("hydrofluoric_acid", "F", 1);
    snt_register_material("aqua_regia", "material.aqua_regia", kGenerationCell, 1, 16753920, 0, 0, 0.0f, "?");
    snt_register_material("lubricant", "material.lubricant", kGenerationCell, 1, 14737536, 0, 0, 0.0f, "?");
    snt_register_material("biomass", "material.biomass", kGenerationCell, 1, 4218912, 0, 0, 0.0f, "?");
    snt_register_material("ethanol", "material.ethanol", kGenerationCell, 1, 14737568, 0, 0, 46.1f, "C2H5OH");
    snt_add_material_element("ethanol", "C", 2);
    snt_add_material_element("ethanol", "H", 6);
    snt_add_material_element("ethanol", "O", 1);
    snt_register_material("oil", "material.oil", kGenerationCell, 1, 1842204, 0, 0, 0.0f, "?");
    snt_register_material("oil_heavy", "material.oil_heavy", kGenerationCell, 1, 2759178, 0, 0, 0.0f, "?");
    snt_register_material("oil_light", "material.oil_light", kGenerationCell, 1, 3813408, 0, 0, 0.0f, "?");
    snt_register_material("fuel_diesel", "material.fuel_diesel", kGenerationCell, 1, 4202496, 0, 0, 0.0f, "?");
    snt_register_material("fuel_rocket", "material.fuel_rocket", kGenerationCell, 1, 6299648, 0, 0, 0.0f, "?");
    snt_register_material("glue", "material.glue", kGenerationCell, 1, 13676640, 0, 0, 0.0f, "?");
    snt_register_material("molten_iron", "material.molten_iron", kGenerationCell, 1, 16736288, 1811, 3134, 55.8f, "Fe");
    snt_add_material_element("molten_iron", "Fe", 1);
    snt_register_material("carbon_dioxide", "material.carbon_dioxide", kGenerationCell, 2, 12632256, 217, 195, 44.0f, "CO2");
    snt_add_material_element("carbon_dioxide", "C", 1);
    snt_add_material_element("carbon_dioxide", "O", 2);
    snt_register_material("carbon_monoxide", "material.carbon_monoxide", kGenerationCell, 2, 10526896, 68, 81, 28.0f, "CO");
    snt_add_material_element("carbon_monoxide", "C", 1);
    snt_add_material_element("carbon_monoxide", "O", 1);
    snt_register_material("sulfur_dioxide", "material.sulfur_dioxide", kGenerationCell, 2, 12640352, 200, 263, 64.1f, "SO2");
    snt_add_material_element("sulfur_dioxide", "S", 1);
    snt_add_material_element("sulfur_dioxide", "O", 2);
    snt_register_material("nitrogen_dioxide", "material.nitrogen_dioxide", kGenerationCell, 2, 14696480, 262, 294, 46.0f, "NO2");
    snt_add_material_element("nitrogen_dioxide", "N", 1);
    snt_add_material_element("nitrogen_dioxide", "O", 2);
    snt_register_material("nitric_oxide", "material.nitric_oxide", kGenerationCell, 2, 10535152, 110, 121, 30.0f, "NO");
    snt_add_material_element("nitric_oxide", "N", 1);
    snt_add_material_element("nitric_oxide", "O", 1);
    snt_register_material("ammonia", "material.ammonia", kGenerationCell, 2, 8446080, 195, 240, 17.0f, "NH3");
    snt_add_material_element("ammonia", "N", 1);
    snt_add_material_element("ammonia", "H", 3);
    snt_register_material("methane", "material.methane", kGenerationCell, 2, 8437952, 91, 112, 16.0f, "CH4");
    snt_add_material_element("methane", "C", 1);
    snt_add_material_element("methane", "H", 4);
    snt_register_material("natural_gas", "material.natural_gas", kGenerationCell, 2, 9478288, 0, 0, 0.0f, "?");
    snt_register_material("hydrogen_sulfide", "material.hydrogen_sulfide", kGenerationCell, 2, 12640320, 188, 213, 34.1f, "H2S");
    snt_add_material_element("hydrogen_sulfide", "H", 2);
    snt_add_material_element("hydrogen_sulfide", "S", 1);
    snt_register_material("ozone", "material.ozone", kGenerationCell, 2, 8429823, 80, 161, 48.0f, "O3");
    snt_add_material_element("ozone", "O", 3);
    snt_register_material("deuterium", "material.deuterium", kGenerationCellPlasma, 3, 8438015, 0, 0, 2.0f, "D2");
    snt_add_material_element("deuterium", "H", 2);
    snt_register_material("tritium", "material.tritium", kGenerationCellPlasma, 3, 8446207, 0, 0, 3.0f, "T2");
    snt_add_material_element("tritium", "H", 2);
    snt_register_material("helium_3", "material.helium_3", kGenerationCellPlasma, 3, 12640511, 0, 0, 3.0f, "He3");
    snt_add_material_element("helium_3", "He", 1);
    snt_register_material("plasma_nitrogen", "material.plasma_nitrogen", kGenerationCellPlasma, 3, 10539263, 0, 0, 0.0f, "N+");
    snt_add_material_element("plasma_nitrogen", "N", 1);
    snt_register_material("plasma_oxygen", "material.plasma_oxygen", kGenerationCellPlasma, 3, 8438015, 0, 0, 0.0f, "O+");
    snt_add_material_element("plasma_oxygen", "O", 1);
    snt_register_material("plasma_helium", "material.plasma_helium", kGenerationCellPlasma, 3, 12640511, 0, 0, 0.0f, "He+");
    snt_add_material_element("plasma_helium", "He", 1);
    snt_register_material("ethylene", "material.ethylene", kGenerationCell, 2, 10539168, 104, 169, 28.1f, "C2H4");
    snt_add_material_element("ethylene", "C", 2);
    snt_add_material_element("ethylene", "H", 4);
    snt_register_material("propylene", "material.propylene", kGenerationCell, 2, 9486496, 88, 226, 42.1f, "C3H6");
    snt_add_material_element("propylene", "C", 3);
    snt_add_material_element("propylene", "H", 6);
    snt_register_material("benzene", "material.benzene", kGenerationCell, 1, 12623936, 279, 353, 78.1f, "C6H6");
    snt_add_material_element("benzene", "C", 6);
    snt_add_material_element("benzene", "H", 6);
    snt_register_material("toluene", "material.toluene", kGenerationCell, 1, 11571264, 178, 384, 92.1f, "C7H8");
    snt_add_material_element("toluene", "C", 7);
    snt_add_material_element("toluene", "H", 8);
    snt_register_material("phenol", "material.phenol", kGenerationCell, 1, 13672544, 314, 455, 94.1f, "C6H5OH");
    snt_add_material_element("phenol", "C", 6);
    snt_add_material_element("phenol", "H", 6);
    snt_add_material_element("phenol", "O", 1);
    snt_register_material("formaldehyde", "material.formaldehyde", kGenerationCell, 2, 12632224, 181, 254, 30.0f, "CH2O");
    snt_add_material_element("formaldehyde", "C", 1);
    snt_add_material_element("formaldehyde", "H", 2);
    snt_add_material_element("formaldehyde", "O", 1);
    snt_register_material("acetic_acid", "material.acetic_acid", kGenerationCell, 1, 14733472, 290, 391, 60.1f, "C2H4O2");
    snt_add_material_element("acetic_acid", "C", 2);
    snt_add_material_element("acetic_acid", "H", 4);
    snt_add_material_element("acetic_acid", "O", 2);
    snt_register_material("acetone", "material.acetone", kGenerationCell, 1, 14737584, 178, 329, 58.1f, "C3H6O");
    snt_add_material_element("acetone", "C", 3);
    snt_add_material_element("acetone", "H", 6);
    snt_add_material_element("acetone", "O", 1);
    snt_register_material("glycerol", "material.glycerol", kGenerationCell, 1, 14733488, 291, 563, 92.1f, "C3H8O3");
    snt_add_material_element("glycerol", "C", 3);
    snt_add_material_element("glycerol", "H", 8);
    snt_add_material_element("glycerol", "O", 3);
    snt_register_material("vinyl_chloride", "material.vinyl_chloride", kGenerationCell, 2, 10530976, 140, 260, 62.5f, "C2H3Cl");
    snt_add_material_element("vinyl_chloride", "C", 2);
    snt_add_material_element("vinyl_chloride", "H", 3);
    snt_add_material_element("vinyl_chloride", "Cl", 1);
    snt_register_material("styrene", "material.styrene", kGenerationCell, 1, 12623968, 242, 418, 104.2f, "C8H8");
    snt_add_material_element("styrene", "C", 8);
    snt_add_material_element("styrene", "H", 8);
    snt_register_material("methanol", "material.methanol", kGenerationCell, 1, 12636352, 176, 338, 32.0f, "CH3OH");
    snt_add_material_element("methanol", "C", 1);
    snt_add_material_element("methanol", "H", 4);
    snt_add_material_element("methanol", "O", 1);
    snt_register_material("ethane", "material.ethane", kGenerationCell, 2, 9482416, 90, 185, 30.1f, "C2H6");
    snt_add_material_element("ethane", "C", 2);
    snt_add_material_element("ethane", "H", 6);
    snt_register_material("propane", "material.propane", kGenerationCell, 2, 9482400, 86, 231, 44.1f, "C3H8");
    snt_add_material_element("propane", "C", 3);
    snt_add_material_element("propane", "H", 8);
    snt_register_material("butane", "material.butane", kGenerationCell, 2, 9482400, 135, 273, 58.1f, "C4H10");
    snt_add_material_element("butane", "C", 4);
    snt_add_material_element("butane", "H", 10);
    snt_register_material("butadiene", "material.butadiene", kGenerationCell, 2, 10535072, 164, 269, 54.1f, "C4H6");
    snt_add_material_element("butadiene", "C", 4);
    snt_add_material_element("butadiene", "H", 6);
    snt_register_material("isoprene", "material.isoprene", kGenerationCell, 1, 12624000, 127, 307, 68.1f, "C5H8");
    snt_add_material_element("isoprene", "C", 5);
    snt_add_material_element("isoprene", "H", 8);
    snt_register_material("naphthalene", "material.naphthalene", kGenerationDust, 0, 13684960, 353, 491, 128.2f, "C10H8");
    snt_add_material_element("naphthalene", "C", 10);
    snt_add_material_element("naphthalene", "H", 8);
    snt_register_material("aniline", "material.aniline", kGenerationCell, 1, 12623968, 267, 457, 93.1f, "C6H5NH2");
    snt_add_material_element("aniline", "C", 6);
    snt_add_material_element("aniline", "H", 7);
    snt_add_material_element("aniline", "N", 1);
    snt_register_material("chloroform", "material.chloroform", kGenerationCell, 1, 12636352, 210, 334, 119.4f, "CHCl3");
    snt_add_material_element("chloroform", "C", 1);
    snt_add_material_element("chloroform", "H", 1);
    snt_add_material_element("chloroform", "Cl", 3);
    snt_register_material("carbon_tetrachloride", "material.carbon_tetrachloride", kGenerationCell, 1, 14737632, 250, 350, 153.8f, "CCl4");
    snt_add_material_element("carbon_tetrachloride", "C", 1);
    snt_add_material_element("carbon_tetrachloride", "Cl", 4);
    snt_register_material("ethylene_glycol", "material.ethylene_glycol", kGenerationCell, 1, 13689040, 260, 470, 62.1f, "C2H6O2");
    snt_add_material_element("ethylene_glycol", "C", 2);
    snt_add_material_element("ethylene_glycol", "H", 6);
    snt_add_material_element("ethylene_glycol", "O", 2);
    snt_register_material("dimethyl_ether", "material.dimethyl_ether", kGenerationCell, 2, 10535104, 132, 248, 46.1f, "C2H6O");
    snt_add_material_element("dimethyl_ether", "C", 2);
    snt_add_material_element("dimethyl_ether", "H", 6);
    snt_add_material_element("dimethyl_ether", "O", 1);
    snt_register_material("wood", "material.wood", kGenerationDustBlockPlateRod, 0, 9133628, 0, 0, 0.5f, "C6H10O5");
    snt_register_material("granite", "material.granite", kGenerationDust, 0, 10524816, 0, 0, 2.7f, "SiO2+Al2O3");
    snt_register_material("basalt", "material.basalt", kGenerationDust, 0, 5263440, 0, 0, 3.0f, "SiO2+FeO");
    snt_register_material("marble", "material.marble", kGenerationDust, 0, 15261912, 0, 0, 2.7f, "CaCO3");
    snt_register_material("sandstone", "material.sandstone", kGenerationDust, 0, 13150320, 0, 0, 2.3f, "SiO2");
    snt_register_material("shale", "material.shale", kGenerationDust, 0, 5922896, 0, 0, 2.5f, "SiO2+Al2O3");
    snt_register_material("komatiite", "material.komatiite", kGenerationDust, 0, 3821616, 0, 0, 3.2f, "MgO+SiO2");
    snt_register_material("regolith", "material.regolith", kGenerationDust, 0, 10510400, 0, 0, 1.8f, "SiO2+Fe2O3");
    snt_register_material("anorthosite", "material.anorthosite", kGenerationDust, 0, 12632264, 0, 0, 2.7f, "CaAl2Si2O8");
    snt_register_material("alumina", "material.alumina", kGenerationDust, 0, 16777215, 2345, 3250, 102.0f, "Al2O3");
    snt_add_material_element("alumina", "Al", 2);
    snt_add_material_element("alumina", "O", 3);
    snt_register_material("magnesia", "material.magnesia", kGenerationDust, 0, 15790320, 3125, 3870, 40.3f, "MgO");
    snt_add_material_element("magnesia", "Mg", 1);
    snt_add_material_element("magnesia", "O", 1);
    snt_register_material("quicklime", "material.quicklime", kGenerationDust, 0, 16316656, 2845, 3850, 56.1f, "CaO");
    snt_add_material_element("quicklime", "Ca", 1);
    snt_add_material_element("quicklime", "O", 1);
    snt_register_material("zinc_oxide", "material.zinc_oxide", kGenerationDust, 0, 15790304, 2248, 2630, 81.4f, "ZnO");
    snt_add_material_element("zinc_oxide", "Zn", 1);
    snt_add_material_element("zinc_oxide", "O", 1);
    snt_register_material("cupric_oxide", "material.cupric_oxide", kGenerationDust, 0, 2105376, 1599, 2270, 79.5f, "CuO");
    snt_add_material_element("cupric_oxide", "Cu", 1);
    snt_add_material_element("cupric_oxide", "O", 1);
    snt_register_material("cuprous_oxide", "material.cuprous_oxide", kGenerationDust, 0, 12591136, 1508, 2070, 143.1f, "Cu2O");
    snt_add_material_element("cuprous_oxide", "Cu", 2);
    snt_add_material_element("cuprous_oxide", "O", 1);
    snt_register_material("nickel_oxide", "material.nickel_oxide", kGenerationDust, 0, 7377008, 2228, 2370, 74.7f, "NiO");
    snt_add_material_element("nickel_oxide", "Ni", 1);
    snt_add_material_element("nickel_oxide", "O", 1);
    snt_register_material("litharge", "material.litharge", kGenerationDust, 0, 12607520, 1161, 1745, 223.2f, "PbO");
    snt_add_material_element("litharge", "Pb", 1);
    snt_add_material_element("litharge", "O", 1);
    snt_register_material("lead_dioxide", "material.lead_dioxide", kGenerationDust, 0, 6307872, 563, 0, 239.2f, "PbO2");
    snt_add_material_element("lead_dioxide", "Pb", 1);
    snt_add_material_element("lead_dioxide", "O", 2);
    snt_register_material("chromium_oxide", "material.chromium_oxide", kGenerationDust, 0, 4227136, 2708, 3270, 152.0f, "Cr2O3");
    snt_add_material_element("chromium_oxide", "Cr", 2);
    snt_add_material_element("chromium_oxide", "O", 3);
    snt_register_material("manganous_oxide", "material.manganous_oxide", kGenerationDust, 0, 4227136, 1945, 3570, 70.9f, "MnO");
    snt_add_material_element("manganous_oxide", "Mn", 1);
    snt_add_material_element("manganous_oxide", "O", 1);
    snt_register_material("manganese_dioxide", "material.manganese_dioxide", kGenerationDust, 0, 2105376, 808, 0, 86.9f, "MnO2");
    snt_add_material_element("manganese_dioxide", "Mn", 1);
    snt_add_material_element("manganese_dioxide", "O", 2);
    snt_register_material("cobalt_oxide", "material.cobalt_oxide", kGenerationDust, 0, 2105376, 2203, 2370, 74.9f, "CoO");
    snt_add_material_element("cobalt_oxide", "Co", 1);
    snt_add_material_element("cobalt_oxide", "O", 1);
    snt_register_material("silver_oxide", "material.silver_oxide", kGenerationDust, 0, 8413248, 553, 0, 231.7f, "Ag2O");
    snt_add_material_element("silver_oxide", "Ag", 2);
    snt_add_material_element("silver_oxide", "O", 1);
    snt_register_material("tungsten_trioxide", "material.tungsten_trioxide", kGenerationDust, 0, 12632160, 1746, 2270, 231.8f, "WO3");
    snt_add_material_element("tungsten_trioxide", "W", 1);
    snt_add_material_element("tungsten_trioxide", "O", 3);
    snt_register_material("molybdenum_trioxide", "material.molybdenum_trioxide", kGenerationDust, 0, 14737648, 1068, 1428, 144.0f, "MoO3");
    snt_add_material_element("molybdenum_trioxide", "Mo", 1);
    snt_add_material_element("molybdenum_trioxide", "O", 3);
    snt_register_material("vanadium_pentoxide", "material.vanadium_pentoxide", kGenerationDust, 0, 14712864, 943, 2270, 181.9f, "V2O5");
    snt_add_material_element("vanadium_pentoxide", "V", 2);
    snt_add_material_element("vanadium_pentoxide", "O", 5);
    snt_register_material("niobium_pentoxide", "material.niobium_pentoxide", kGenerationDust, 0, 15788272, 1785, 3270, 265.8f, "Nb2O5");
    snt_add_material_element("niobium_pentoxide", "Nb", 2);
    snt_add_material_element("niobium_pentoxide", "O", 5);
    snt_register_material("tantalum_pentoxide", "material.tantalum_pentoxide", kGenerationDust, 0, 15790320, 2072, 3270, 441.9f, "Ta2O5");
    snt_add_material_element("tantalum_pentoxide", "Ta", 2);
    snt_add_material_element("tantalum_pentoxide", "O", 5);
    snt_register_material("antimony_trioxide", "material.antimony_trioxide", kGenerationDust, 0, 15790320, 929, 1725, 291.5f, "Sb2O3");
    snt_add_material_element("antimony_trioxide", "Sb", 2);
    snt_add_material_element("antimony_trioxide", "O", 3);
    snt_register_material("bismuth_trioxide", "material.bismuth_trioxide", kGenerationDust, 0, 14737504, 1090, 2170, 466.0f, "Bi2O3");
    snt_add_material_element("bismuth_trioxide", "Bi", 2);
    snt_add_material_element("bismuth_trioxide", "O", 3);
    snt_register_material("beryllia", "material.beryllia", kGenerationDust, 0, 15790320, 2851, 4170, 25.0f, "BeO");
    snt_add_material_element("beryllia", "Be", 1);
    snt_add_material_element("beryllia", "O", 1);
    snt_register_material("boron_trioxide", "material.boron_trioxide", kGenerationDust, 0, 15263976, 723, 2320, 69.6f, "B2O3");
    snt_add_material_element("boron_trioxide", "B", 2);
    snt_add_material_element("boron_trioxide", "O", 3);
    snt_register_material("phosphorus_pentoxide", "material.phosphorus_pentoxide", kGenerationDust, 0, 15790320, 613, 633, 142.0f, "P2O5");
    snt_add_material_element("phosphorus_pentoxide", "P", 2);
    snt_add_material_element("phosphorus_pentoxide", "O", 5);
    snt_register_material("sulfur_trioxide", "material.sulfur_trioxide", kGenerationCell, 1, 14737632, 290, 318, 80.1f, "SO3");
    snt_add_material_element("sulfur_trioxide", "S", 1);
    snt_add_material_element("sulfur_trioxide", "O", 3);
    snt_register_material("dinitrogen_monoxide", "material.dinitrogen_monoxide", kGenerationCell, 2, 12636400, 182, 185, 44.0f, "N2O");
    snt_add_material_element("dinitrogen_monoxide", "N", 2);
    snt_add_material_element("dinitrogen_monoxide", "O", 1);
    snt_register_material("chlorine_dioxide", "material.chlorine_dioxide", kGenerationCell, 2, 15786048, 214, 284, 67.5f, "ClO2");
    snt_add_material_element("chlorine_dioxide", "Cl", 1);
    snt_add_material_element("chlorine_dioxide", "O", 2);
    snt_register_material("iron_ii_oxide", "material.iron_ii_oxide", kGenerationDust, 0, 2105376, 1650, 2773, 71.8f, "FeO");
    snt_add_material_element("iron_ii_oxide", "Fe", 1);
    snt_add_material_element("iron_ii_oxide", "O", 1);
    snt_register_material("iron_iii_oxide", "material.iron_iii_oxide", kGenerationDust, 0, 12599328, 1838, 1273, 159.7f, "Fe2O3");
    snt_add_material_element("iron_iii_oxide", "Fe", 2);
    snt_add_material_element("iron_iii_oxide", "O", 3);
    snt_register_material("uranium_dioxide", "material.uranium_dioxide", kGenerationDust, 0, 4202528, 3140, 3770, 270.0f, "UO2");
    snt_add_material_element("uranium_dioxide", "U", 1);
    snt_add_material_element("uranium_dioxide", "O", 2);
    snt_register_material("thorium_dioxide", "material.thorium_dioxide", kGenerationDust, 0, 15261920, 3660, 4400, 264.0f, "ThO2");
    snt_add_material_element("thorium_dioxide", "Th", 1);
    snt_add_material_element("thorium_dioxide", "O", 2);
    snt_register_material("zirconia", "material.zirconia", kGenerationDust, 0, 15790320, 2988, 5273, 123.2f, "ZrO2");
    snt_add_material_element("zirconia", "Zr", 1);
    snt_add_material_element("zirconia", "O", 2);
    snt_register_material("tin_dioxide", "material.tin_dioxide", kGenerationDust, 0, 15790320, 1903, 3270, 150.7f, "SnO2");
    snt_add_material_element("tin_dioxide", "Sn", 1);
    snt_add_material_element("tin_dioxide", "O", 2);
    snt_register_material("titania", "material.titania", kGenerationDust, 0, 15790320, 2128, 3245, 79.9f, "TiO2");
    snt_add_material_element("titania", "Ti", 1);
    snt_add_material_element("titania", "O", 2);
    snt_register_material("chromium_trioxide", "material.chromium_trioxide", kGenerationDust, 0, 12591136, 470, 523, 100.0f, "CrO3");
    snt_add_material_element("chromium_trioxide", "Cr", 1);
    snt_add_material_element("chromium_trioxide", "O", 3);
    snt_register_material("osmium_tetroxide", "material.osmium_tetroxide", kGenerationDust, 0, 14739616, 313, 403, 254.2f, "OsO4");
    snt_add_material_element("osmium_tetroxide", "Os", 1);
    snt_add_material_element("osmium_tetroxide", "O", 4);
    snt_register_material("silicon_dioxide", "material.silicon_dioxide", kGenerationDust, 0, 14737632, 1986, 3223, 60.1f, "SiO2");
    snt_add_material_element("silicon_dioxide", "Si", 1);
    snt_add_material_element("silicon_dioxide", "O", 2);
    snt_register_material("sodium_hydroxide", "material.sodium_hydroxide", kGenerationDust, 0, 15790320, 591, 1661, 40.0f, "NaOH");
    snt_add_material_element("sodium_hydroxide", "Na", 1);
    snt_add_material_element("sodium_hydroxide", "O", 1);
    snt_add_material_element("sodium_hydroxide", "H", 1);
    snt_register_material("potassium_hydroxide", "material.potassium_hydroxide", kGenerationDust, 0, 15790320, 679, 1608, 56.1f, "KOH");
    snt_add_material_element("potassium_hydroxide", "K", 1);
    snt_add_material_element("potassium_hydroxide", "O", 1);
    snt_add_material_element("potassium_hydroxide", "H", 1);
    snt_register_material("calcium_hydroxide", "material.calcium_hydroxide", kGenerationDust, 0, 15790304, 839, 0, 74.1f, "Ca(OH)2");
    snt_add_material_element("calcium_hydroxide", "Ca", 1);
    snt_add_material_element("calcium_hydroxide", "O", 2);
    snt_add_material_element("calcium_hydroxide", "H", 2);
    snt_register_material("magnesium_hydroxide", "material.magnesium_hydroxide", kGenerationDust, 0, 15790320, 623, 0, 58.3f, "Mg(OH)2");
    snt_add_material_element("magnesium_hydroxide", "Mg", 1);
    snt_add_material_element("magnesium_hydroxide", "O", 2);
    snt_add_material_element("magnesium_hydroxide", "H", 2);
    snt_register_material("aluminum_hydroxide", "material.aluminum_hydroxide", kGenerationDust, 0, 15790320, 573, 0, 78.0f, "Al(OH)3");
    snt_add_material_element("aluminum_hydroxide", "Al", 1);
    snt_add_material_element("aluminum_hydroxide", "O", 3);
    snt_add_material_element("aluminum_hydroxide", "H", 3);
    snt_register_material("iron_ii_hydroxide", "material.iron_ii_hydroxide", kGenerationDust, 0, 4227136, 0, 0, 89.9f, "Fe(OH)2");
    snt_add_material_element("iron_ii_hydroxide", "Fe", 1);
    snt_add_material_element("iron_ii_hydroxide", "O", 2);
    snt_add_material_element("iron_ii_hydroxide", "H", 2);
    snt_register_material("iron_iii_hydroxide", "material.iron_iii_hydroxide", kGenerationDust, 0, 8405024, 0, 0, 106.9f, "Fe(OH)3");
    snt_add_material_element("iron_iii_hydroxide", "Fe", 1);
    snt_add_material_element("iron_iii_hydroxide", "O", 3);
    snt_add_material_element("iron_iii_hydroxide", "H", 3);
    snt_register_material("soda_ash", "material.soda_ash", kGenerationDust, 0, 15790320, 1124, 1870, 106.0f, "Na2CO3");
    snt_add_material_element("soda_ash", "Na", 2);
    snt_add_material_element("soda_ash", "C", 1);
    snt_add_material_element("soda_ash", "O", 3);
    snt_register_material("sodium_bicarbonate", "material.sodium_bicarbonate", kGenerationDust, 0, 15263976, 543, 0, 84.0f, "NaHCO3");
    snt_add_material_element("sodium_bicarbonate", "Na", 1);
    snt_add_material_element("sodium_bicarbonate", "H", 1);
    snt_add_material_element("sodium_bicarbonate", "C", 1);
    snt_add_material_element("sodium_bicarbonate", "O", 3);
    snt_register_material("saltpeter", "material.saltpeter", kGenerationDustBlock, 0, 15790320, 607, 0, 101.1f, "KNO3");
    snt_add_material_element("saltpeter", "K", 1);
    snt_add_material_element("saltpeter", "N", 1);
    snt_add_material_element("saltpeter", "O", 3);
    snt_register_material("sodium_nitrate", "material.sodium_nitrate", kGenerationDust, 0, 15790320, 581, 0, 85.0f, "NaNO3");
    snt_add_material_element("sodium_nitrate", "Na", 1);
    snt_add_material_element("sodium_nitrate", "N", 1);
    snt_add_material_element("sodium_nitrate", "O", 3);
    snt_register_material("ammonium_nitrate", "material.ammonium_nitrate", kGenerationDust, 0, 15790320, 442, 483, 80.0f, "NH4NO3");
    snt_add_material_element("ammonium_nitrate", "N", 2);
    snt_add_material_element("ammonium_nitrate", "H", 4);
    snt_add_material_element("ammonium_nitrate", "O", 3);
    snt_register_material("ammonium_chloride", "material.ammonium_chloride", kGenerationDust, 0, 15790320, 611, 793, 53.5f, "NH4Cl");
    snt_add_material_element("ammonium_chloride", "N", 1);
    snt_add_material_element("ammonium_chloride", "H", 4);
    snt_add_material_element("ammonium_chloride", "Cl", 1);
    snt_register_material("calcium_sulfate", "material.calcium_sulfate", kGenerationDust, 0, 15790320, 1723, 0, 136.1f, "CaSO4");
    snt_add_material_element("calcium_sulfate", "Ca", 1);
    snt_add_material_element("calcium_sulfate", "S", 1);
    snt_add_material_element("calcium_sulfate", "O", 4);
    snt_register_material("magnesium_sulfate", "material.magnesium_sulfate", kGenerationDust, 0, 15790320, 1385, 0, 120.4f, "MgSO4");
    snt_add_material_element("magnesium_sulfate", "Mg", 1);
    snt_add_material_element("magnesium_sulfate", "S", 1);
    snt_add_material_element("magnesium_sulfate", "O", 4);
    snt_register_material("sodium_sulfate", "material.sodium_sulfate", kGenerationDust, 0, 15790320, 1157, 1700, 142.0f, "Na2SO4");
    snt_add_material_element("sodium_sulfate", "Na", 2);
    snt_add_material_element("sodium_sulfate", "S", 1);
    snt_add_material_element("sodium_sulfate", "O", 4);
    snt_register_material("copper_sulfate", "material.copper_sulfate", kGenerationDust, 0, 4210880, 773, 0, 159.6f, "CuSO4");
    snt_add_material_element("copper_sulfate", "Cu", 1);
    snt_add_material_element("copper_sulfate", "S", 1);
    snt_add_material_element("copper_sulfate", "O", 4);
    snt_register_material("iron_ii_sulfate", "material.iron_ii_sulfate", kGenerationDust, 0, 6336608, 673, 0, 151.9f, "FeSO4");
    snt_add_material_element("iron_ii_sulfate", "Fe", 1);
    snt_add_material_element("iron_ii_sulfate", "S", 1);
    snt_add_material_element("iron_ii_sulfate", "O", 4);
    snt_register_material("iron_iii_sulfate", "material.iron_iii_sulfate", kGenerationDust, 0, 12632160, 753, 0, 399.9f, "Fe2(SO4)3");
    snt_add_material_element("iron_iii_sulfate", "Fe", 2);
    snt_add_material_element("iron_iii_sulfate", "S", 3);
    snt_add_material_element("iron_iii_sulfate", "O", 12);
    snt_register_material("zinc_sulfate", "material.zinc_sulfate", kGenerationDust, 0, 15790320, 773, 0, 161.5f, "ZnSO4");
    snt_add_material_element("zinc_sulfate", "Zn", 1);
    snt_add_material_element("zinc_sulfate", "S", 1);
    snt_add_material_element("zinc_sulfate", "O", 4);
    snt_register_material("nickel_sulfate", "material.nickel_sulfate", kGenerationDust, 0, 8441984, 1053, 0, 154.8f, "NiSO4");
    snt_add_material_element("nickel_sulfate", "Ni", 1);
    snt_add_material_element("nickel_sulfate", "S", 1);
    snt_add_material_element("nickel_sulfate", "O", 4);
    snt_register_material("cobalt_sulfate", "material.cobalt_sulfate", kGenerationDust, 0, 12599392, 1073, 0, 155.0f, "CoSO4");
    snt_add_material_element("cobalt_sulfate", "Co", 1);
    snt_add_material_element("cobalt_sulfate", "S", 1);
    snt_add_material_element("cobalt_sulfate", "O", 4);
    snt_register_material("manganese_sulfate", "material.manganese_sulfate", kGenerationDust, 0, 13672624, 973, 0, 151.0f, "MnSO4");
    snt_add_material_element("manganese_sulfate", "Mn", 1);
    snt_add_material_element("manganese_sulfate", "S", 1);
    snt_add_material_element("manganese_sulfate", "O", 4);
    snt_register_material("aluminum_sulfate", "material.aluminum_sulfate", kGenerationDust, 0, 15790320, 1043, 0, 342.2f, "Al2(SO4)3");
    snt_add_material_element("aluminum_sulfate", "Al", 2);
    snt_add_material_element("aluminum_sulfate", "S", 3);
    snt_add_material_element("aluminum_sulfate", "O", 12);
    snt_register_material("sodium_chloride", "material.sodium_chloride", kGenerationDust, 0, 15790320, 1074, 1738, 58.4f, "NaCl");
    snt_add_material_element("sodium_chloride", "Na", 1);
    snt_add_material_element("sodium_chloride", "Cl", 1);
    snt_register_material("potassium_chloride", "material.potassium_chloride", kGenerationDust, 0, 15790320, 1043, 1690, 74.6f, "KCl");
    snt_add_material_element("potassium_chloride", "K", 1);
    snt_add_material_element("potassium_chloride", "Cl", 1);
    snt_register_material("calcium_carbonate", "material.calcium_carbonate", kGenerationDust, 0, 16316656, 1612, 0, 100.1f, "CaCO3");
    snt_add_material_element("calcium_carbonate", "Ca", 1);
    snt_add_material_element("calcium_carbonate", "C", 1);
    snt_add_material_element("calcium_carbonate", "O", 3);
    snt_register_material("glass", "material.glass", kGenerationDustBlockPlate, 0, 14739696, 0, 0, 0.0f, "SiO2+Na2O+CaO");
    snt_register_material("borosilicate_glass", "material.borosilicate_glass", kGenerationDustBlockPlate, 0, 14739696, 0, 0, 0.0f, "SiO2+B2O3");
    snt_register_material("concrete", "material.concrete", kGenerationDust, 0, 9474192, 0, 0, 0.0f, "CaO+SiO2");
    snt_register_material("refractory_cement", "material.refractory_cement", kGenerationDust, 0, 10524816, 0, 0, 0.0f, "Al2O3+SiO2");
    snt_register_material("porcelain", "material.porcelain", kGenerationDust, 0, 15788256, 0, 0, 0.0f, "Al2O3+SiO2+K2O");
    snt_register_material("slag", "material.slag", kGenerationDust, 0, 4210752, 0, 0, 0.0f, "CaO+SiO2+Al2O3");
    snt_register_material("redstone", "material.redstone", kGenerationDustBlock, 0, 11538448, 0, 0, 0.0f, "?");
    snt_register_material("rubber", "material.rubber", kGenerationPlate, 0, 2105376, 0, 0, 0.0f, "(C5H8)n");
    snt_add_material_element("rubber", "C", 5);
    snt_add_material_element("rubber", "H", 8);
    snt_register_material("polyethylene", "material.polyethylene", kGenerationPlate, 0, 15266548, 0, 0, 0.0f, "(C2H4)n");
    snt_add_material_element("polyethylene", "C", 2);
    snt_add_material_element("polyethylene", "H", 4);
    snt_register_material("glowstone", "material.glowstone", kGenerationDustBlock, 0, 16766554, 0, 0, 0.0f, "?");
    snt_register_material("wrought_iron", "material.wrought_iron", kGenerationDustMetalWireBlock, 0, 9078144, 1811, 3134, 55.8f, "Fe");
    snt_add_material_element("wrought_iron", "Fe", 1);
    snt_register_item("crushed.magnetite", "item.compound.crushed_magnetite", 64);
    snt_set_item_presentation("crushed.magnetite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.pyrite", "item.compound.crushed_pyrite", 64);
    snt_set_item_presentation("crushed.pyrite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.bauxite", "item.compound.crushed_bauxite", 64);
    snt_set_item_presentation("crushed.bauxite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.cassiterite", "item.compound.crushed_cassiterite", 64);
    snt_set_item_presentation("crushed.cassiterite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.ilmenite", "item.compound.crushed_ilmenite", 64);
    snt_set_item_presentation("crushed.ilmenite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.pentlandite", "item.compound.crushed_pentlandite", 64);
    snt_set_item_presentation("crushed.pentlandite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.chalcopyrite", "item.compound.crushed_chalcopyrite", 64);
    snt_set_item_presentation("crushed.chalcopyrite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.sphalerite", "item.compound.crushed_sphalerite", 64);
    snt_set_item_presentation("crushed.sphalerite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.galena", "item.compound.crushed_galena", 64);
    snt_set_item_presentation("crushed.galena", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("dust.cinnabar", "item.compound.dust_cinnabar", 64);
    snt_set_item_presentation("dust.cinnabar", 0, "material_sets/generic/dust_base_32.png", "", 11579568, true);
    snt_register_item("dust.fluorite", "item.compound.dust_fluorite", 64);
    snt_set_item_presentation("dust.fluorite", 0, "material_sets/generic/dust_base_32.png", "", 11579568, true);
    snt_register_item("dust.graphite", "item.compound.dust_graphite", 64);
    snt_set_item_presentation("dust.graphite", 0, "material_sets/generic/dust_base_32.png", "", 11579568, true);
    snt_register_item("dust.salt", "item.compound.dust_salt", 64);
    snt_set_item_presentation("dust.salt", 0, "material_sets/generic/dust_base_32.png", "", 11579568, true);
    snt_register_item("crushed.hematite", "item.compound.crushed_hematite", 64);
    snt_set_item_presentation("crushed.hematite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.malachite", "item.compound.crushed_malachite", 64);
    snt_set_item_presentation("crushed.malachite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.pyrolusite", "item.compound.crushed_pyrolusite", 64);
    snt_set_item_presentation("crushed.pyrolusite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.wolframite", "item.compound.crushed_wolframite", 64);
    snt_set_item_presentation("crushed.wolframite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.rutile", "item.compound.crushed_rutile", 64);
    snt_set_item_presentation("crushed.rutile", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.sperrylite", "item.compound.crushed_sperrylite", 64);
    snt_set_item_presentation("crushed.sperrylite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.cobaltite", "item.compound.crushed_cobaltite", 64);
    snt_set_item_presentation("crushed.cobaltite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.uraninite", "item.compound.crushed_uraninite", 64);
    snt_set_item_presentation("crushed.uraninite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.spodumene", "item.compound.crushed_spodumene", 64);
    snt_set_item_presentation("crushed.spodumene", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.bertrandite", "item.compound.crushed_bertrandite", 64);
    snt_set_item_presentation("crushed.bertrandite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.kernite", "item.compound.crushed_kernite", 64);
    snt_set_item_presentation("crushed.kernite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.magnesite", "item.compound.crushed_magnesite", 64);
    snt_set_item_presentation("crushed.magnesite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.silica", "item.compound.crushed_silica", 64);
    snt_set_item_presentation("crushed.silica", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.apatite", "item.compound.crushed_apatite", 64);
    snt_set_item_presentation("crushed.apatite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.sylvite", "item.compound.crushed_sylvite", 64);
    snt_set_item_presentation("crushed.sylvite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.calcite", "item.compound.crushed_calcite", 64);
    snt_set_item_presentation("crushed.calcite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.thortveitite", "item.compound.crushed_thortveitite", 64);
    snt_set_item_presentation("crushed.thortveitite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.patronite", "item.compound.crushed_patronite", 64);
    snt_set_item_presentation("crushed.patronite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.chromite", "item.compound.crushed_chromite", 64);
    snt_set_item_presentation("crushed.chromite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.gallite", "item.compound.crushed_gallite", 64);
    snt_set_item_presentation("crushed.gallite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.germanite", "item.compound.crushed_germanite", 64);
    snt_set_item_presentation("crushed.germanite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.arsenopyrite", "item.compound.crushed_arsenopyrite", 64);
    snt_set_item_presentation("crushed.arsenopyrite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.clausthalite", "item.compound.crushed_clausthalite", 64);
    snt_set_item_presentation("crushed.clausthalite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.bromargyrite", "item.compound.crushed_bromargyrite", 64);
    snt_set_item_presentation("crushed.bromargyrite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.celestine", "item.compound.crushed_celestine", 64);
    snt_set_item_presentation("crushed.celestine", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.xenotime", "item.compound.crushed_xenotime", 64);
    snt_set_item_presentation("crushed.xenotime", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.zircon", "item.compound.crushed_zircon", 64);
    snt_set_item_presentation("crushed.zircon", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.columbite", "item.compound.crushed_columbite", 64);
    snt_set_item_presentation("crushed.columbite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.molybdenite", "item.compound.crushed_molybdenite", 64);
    snt_set_item_presentation("crushed.molybdenite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.laurite", "item.compound.crushed_laurite", 64);
    snt_set_item_presentation("crushed.laurite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.stibiopalladinite", "item.compound.crushed_stibiopalladinite", 64);
    snt_set_item_presentation("crushed.stibiopalladinite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.rhodium_oxide", "item.compound.crushed_rhodium_oxide", 64);
    snt_set_item_presentation("crushed.rhodium_oxide", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.greenockite", "item.compound.crushed_greenockite", 64);
    snt_set_item_presentation("crushed.greenockite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.roquesite", "item.compound.crushed_roquesite", 64);
    snt_set_item_presentation("crushed.roquesite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.stibnite", "item.compound.crushed_stibnite", 64);
    snt_set_item_presentation("crushed.stibnite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.calaverite", "item.compound.crushed_calaverite", 64);
    snt_set_item_presentation("crushed.calaverite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.iodargyrite", "item.compound.crushed_iodargyrite", 64);
    snt_set_item_presentation("crushed.iodargyrite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.pollucite", "item.compound.crushed_pollucite", 64);
    snt_set_item_presentation("crushed.pollucite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.barite", "item.compound.crushed_barite", 64);
    snt_set_item_presentation("crushed.barite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.monazite", "item.compound.crushed_monazite", 64);
    snt_set_item_presentation("crushed.monazite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.baddeleyite", "item.compound.crushed_baddeleyite", 64);
    snt_set_item_presentation("crushed.baddeleyite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.tantalite", "item.compound.crushed_tantalite", 64);
    snt_set_item_presentation("crushed.tantalite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.rheniite", "item.compound.crushed_rheniite", 64);
    snt_set_item_presentation("crushed.rheniite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.osmiridium", "item.compound.crushed_osmiridium", 64);
    snt_set_item_presentation("crushed.osmiridium", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.iridium_oxide", "item.compound.crushed_iridium_oxide", 64);
    snt_set_item_presentation("crushed.iridium_oxide", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.thorite", "item.compound.crushed_thorite", 64);
    snt_set_item_presentation("crushed.thorite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.lepidolite", "item.compound.crushed_lepidolite", 64);
    snt_set_item_presentation("crushed.lepidolite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.bismuthinite", "item.compound.crushed_bismuthinite", 64);
    snt_set_item_presentation("crushed.bismuthinite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.crookesite", "item.compound.crushed_crookesite", 64);
    snt_set_item_presentation("crushed.crookesite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("crushed.phosphorite", "item.compound.crushed_phosphorite", 64);
    snt_set_item_presentation("crushed.phosphorite", 0, "material_sets/generic/crushed_base_32.png", "", 11579568, true);
    snt_register_item("dust.ash", "item.compound.dust_ash", 64);
    snt_set_item_presentation("dust.ash", 0, "material_sets/generic/dust_base_32.png", "", 11579568, true);
    snt_register_item("dust.sawdust", "item.compound.dust_sawdust", 64);
    snt_set_item_presentation("dust.sawdust", 0, "material_sets/generic/dust_base_32.png", "", 11579568, true);
    snt_set_material_form_presentation("wood", 0, "item.wood_log", 64, "materials/wood_log_icon_32.png", "", 16777215, false);
    snt_set_material_form_presentation("wood", 16, "item.wood_plank", 64, "materials/wood_plank_icon_32.png", "", 16777215, false);
    snt_set_material_form_presentation("wood", 19, "item.stick", 64, "materials/stick_icon_32.png", "", 16777215, false);
    snt_set_material_form_presentation("coal", 8, "item.coal", 64, "material_sets/generic/gem_base_32.png", "", 1710618, true);
    snt_log("Registered 186 non-element materials and 65 compound items");
}
