// Game-owned item and fluid catalog migrated from retired Godot registries.
//
// Ownership: material forms are generated by 00_material_catalog.as. This
// module owns authored non-material items, fluid definitions, presentation,
// and tool behavior. P7 machine/recipe content consumes these normalized
// keys, while one content transaction publishes their shared runtime index.

const int kMaterials = 0;
const int kTools = 1;
const int kComponents = 2;
const int kPlaceables = 3;
const int kResources = 4;
const int kFood = 5;

const int kToolNone = 0;
const int kToolPickaxe = 1;
const int kToolAxe = 2;
const int kToolShovel = 3;
const int kToolSword = 4;
const int kToolHoe = 5;
const int kToolKnife = 6;

void register_catalog_item(const string &in id, const string &in title_key,
                           int max_stack, int category,
                           const string &in icon_path) {
    snt_register_item(id, title_key, max_stack);
    snt_set_item_presentation(id, category, icon_path, "", 0xffffff, false);
}

void register_tinted_catalog_item(const string &in id, const string &in title_key,
                                  int max_stack, int category,
                                  const string &in icon_path, int tint_rgb) {
    snt_register_item(id, title_key, max_stack);
    snt_set_item_presentation(id, category, icon_path, "", tint_rgb, true);
}

void register_catalog_tool(const string &in id, const string &in title_key,
                           const string &in icon_path, int tool_type,
                           int mining_level, const string &in material_key,
                           float speed, int durability, float attack_damage) {
    register_catalog_item(id, title_key, 1, kTools, icon_path);
    snt_set_item_tool(id, tool_type, mining_level, material_key, speed,
                      durability, attack_damage);
}

void snt_register() {
    // Core and TFC tool behavior.
    register_catalog_tool("wooden_pickaxe", "wooden_pickaxe",
                          "tools/wooden_pickaxe_icon_32.png", kToolPickaxe,
                          0, "wood", 1.5f, 60, 2.0f);
    register_catalog_tool("stone_pickaxe", "stone_pickaxe",
                          "tools/stone_pickaxe_icon_32.png", kToolPickaxe,
                          1, "stone", 2.0f, 130, 3.0f);
    register_catalog_tool("iron_pickaxe", "iron_pickaxe",
                          "tools/iron_pickaxe_icon_32.png", kToolPickaxe,
                          2, "iron", 3.0f, 250, 4.0f);
    register_catalog_tool("wooden_axe", "wooden_axe",
                          "tools/wooden_axe_icon_32.png", kToolAxe,
                          0, "wood", 1.5f, 60, 3.0f);
    register_catalog_tool("stone_axe", "stone_axe",
                          "tools/stone_axe_icon_32.png", kToolAxe,
                          1, "stone", 2.0f, 130, 4.0f);
    register_catalog_tool("iron_axe", "iron_axe",
                          "tools/iron_axe_icon_32.png", kToolAxe,
                          2, "iron", 3.0f, 250, 5.0f);
    register_catalog_tool("wooden_shovel", "wooden_shovel",
                          "tools/wooden_shovel_icon_32.png", kToolShovel,
                          0, "wood", 1.5f, 60, 1.5f);
    register_catalog_tool("stone_shovel", "stone_shovel",
                          "tools/stone_shovel_icon_32.png", kToolShovel,
                          1, "stone", 2.0f, 130, 2.5f);
    register_catalog_tool("iron_shovel", "iron_shovel",
                          "tools/iron_shovel_icon_32.png", kToolShovel,
                          2, "iron", 3.0f, 250, 3.5f);
    register_catalog_tool("wooden_sword", "wooden_sword",
                          "tools/wooden_sword_icon_32.png", kToolSword,
                          0, "wood", 1.0f, 60, 4.0f);
    register_catalog_tool("stone_sword", "stone_sword",
                          "tools/stone_sword_icon_32.png", kToolSword,
                          1, "stone", 1.0f, 130, 5.0f);
    register_catalog_tool("iron_sword", "iron_sword",
                          "tools/iron_sword_icon_32.png", kToolSword,
                          2, "iron", 1.0f, 250, 6.0f);

    register_catalog_tool("copper_pickaxe", "copper_pickaxe",
                          "tools/copper_pickaxe_icon_32.png", kToolPickaxe,
                          2, "copper", 2.5f, 180, 3.5f);
    register_catalog_tool("copper_axe", "copper_axe",
                          "tools/copper_axe_icon_32.png", kToolAxe,
                          2, "copper", 2.5f, 180, 4.5f);
    register_catalog_tool("copper_shovel", "copper_shovel",
                          "tools/copper_shovel_icon_32.png", kToolShovel,
                          2, "copper", 2.5f, 180, 3.0f);
    register_catalog_tool("copper_sword", "copper_sword",
                          "tools/copper_sword_icon_32.png", kToolSword,
                          2, "copper", 1.0f, 180, 5.5f);
    register_catalog_tool("tin_bronze_pickaxe", "tin_bronze_pickaxe",
                          "tools/tin_bronze_pickaxe_icon_32.png", kToolPickaxe,
                          2, "tin_bronze", 3.5f, 400, 4.5f);
    register_catalog_tool("tin_bronze_axe", "tin_bronze_axe",
                          "tools/tin_bronze_axe_icon_32.png", kToolAxe,
                          2, "tin_bronze", 3.5f, 400, 5.5f);
    register_catalog_tool("bismuth_bronze_pickaxe", "bismuth_bronze_pickaxe",
                          "tools/bismuth_bronze_pickaxe_icon_32.png", kToolPickaxe,
                          2, "bismuth_bronze", 3.0f, 520, 4.2f);
    register_catalog_tool("bismuth_bronze_axe", "bismuth_bronze_axe",
                          "tools/bismuth_bronze_axe_icon_32.png", kToolAxe,
                          2, "bismuth_bronze", 3.0f, 520, 5.2f);
    register_catalog_tool("black_bronze_pickaxe", "black_bronze_pickaxe",
                          "tools/black_bronze_pickaxe_icon_32.png", kToolPickaxe,
                          2, "black_bronze", 3.2f, 460, 4.8f);
    register_catalog_tool("steel_pickaxe", "steel_pickaxe",
                          "tools/steel_pickaxe_icon_32.png", kToolPickaxe,
                          3, "steel", 4.5f, 800, 6.0f);
    register_catalog_tool("steel_axe", "steel_axe",
                          "tools/steel_axe_icon_32.png", kToolAxe,
                          3, "steel", 4.5f, 800, 7.0f);
    register_catalog_tool("steel_shovel", "steel_shovel",
                          "tools/steel_shovel_icon_32.png", kToolShovel,
                          3, "steel", 4.5f, 800, 5.0f);
    register_catalog_tool("steel_sword", "steel_sword",
                          "tools/steel_sword_icon_32.png", kToolSword,
                          3, "steel", 1.0f, 800, 8.0f);
    register_catalog_tool("stone_hoe", "stone_hoe",
                          "tools/stone_hoe_icon_32.png", kToolHoe,
                          1, "stone", 1.5f, 120, 2.0f);
    register_catalog_tool("stone_knife", "stone_knife",
                          "tools/stone_knife_icon_32.png", kToolKnife,
                          1, "stone", 1.0f, 100, 3.0f);

    register_catalog_item("stone_axe_head", "stone_axe_head", 16, kTools,
                          "tools/stone_axe_head_icon_32.png");
    register_catalog_item("stone_shovel_head", "stone_shovel_head", 16, kTools,
                          "tools/stone_shovel_head_icon_32.png");
    register_catalog_item("stone_hoe_head", "stone_hoe_head", 16, kTools,
                          "tools/stone_hoe_head_icon_32.png");
    register_catalog_item("stone_knife_head", "stone_knife_head", 16, kTools,
                          "tools/stone_knife_head_icon_32.png");
    register_catalog_item("flint", "item.flint", 64, kResources,
                          "materials/flint_icon_32.png");
    register_catalog_item("chert", "item.chert", 64, kResources,
                          "materials/chert_icon_32.png");

    // GregTech-style tools and component parts.
    register_catalog_item("gt_hammer", "gt_hammer", 1, kComponents,
                          "tools/gt_hammer_icon_32.png");
    register_catalog_item("gt_wrench", "gt_wrench", 1, kComponents,
                          "tools/gt_wrench_icon_32.png");
    register_catalog_item("gt_file", "gt_file", 1, kComponents,
                          "tools/gt_file_icon_32.png");
    register_catalog_item("gt_screwdriver", "gt_screwdriver", 1, kComponents,
                          "tools/gt_screwdriver_icon_32.png");
    register_catalog_item("gt_saw", "gt_saw", 1, kComponents,
                          "tools/gt_saw_icon_32.png");
    register_catalog_item("gt_wire_cutter", "gt_wire_cutter", 1, kComponents,
                          "tools/gt_wire_cutter_icon_32.png");
    register_catalog_item("gt_crowbar", "gt_crowbar", 1, kComponents,
                          "tools/gt_crowbar_icon_32.png");
    register_catalog_item("gt_soft_mallet", "gt_soft_mallet", 1, kComponents,
                          "tools/gt_soft_mallet_icon_32.png");
    register_catalog_item("gt_hard_hammer", "gt_hard_hammer", 1, kComponents,
                          "tools/gt_hard_hammer_icon_32.png");
    register_catalog_item("machine_hull_basic", "machine_hull_basic", 64, kComponents,
                          "components/basic_machine_hull_icon_32.png");
    register_catalog_item("machine_hull_advanced", "machine_hull_advanced", 64, kComponents,
                          "components/advanced_machine_hull_icon_32.png");
    register_catalog_item("electric_motor_lv", "electric_motor_lv", 64, kComponents,
                          "components/lv_electric_motor_icon_32.png");
    register_catalog_item("electric_piston_lv", "electric_piston_lv", 64, kComponents,
                          "components/lv_electric_piston_icon_32.png");
    register_catalog_item("robot_arm_lv", "robot_arm_lv", 64, kComponents,
                          "components/lv_robot_arm_icon_32.png");
    register_catalog_item("conveyor_module_lv", "conveyor_module_lv", 64, kComponents,
                          "components/lv_conveyor_module_icon_32.png");
    register_catalog_item("pump_lv", "pump_lv", 64, kComponents,
                          "components/lv_pump_icon_32.png");
    register_catalog_item("empty_fluid_cell", "empty_fluid_cell", 64, kComponents,
                          "components/empty_fluid_cell_icon_32.png");
    register_catalog_item("vacuum_tube", "vacuum_tube", 64, kComponents,
                          "circuits/vacuum_tube_icon_32.png");
    register_catalog_item("circuit_primitive", "circuit_primitive", 64, kComponents,
                          "circuits/primitive_circuit_icon_32.png");
    register_catalog_item("circuit_basic", "circuit_basic", 64, kComponents,
                          "circuits/basic_circuit_icon_32.png");
    register_catalog_item("circuit_good", "circuit_good", 64, kComponents,
                          "circuits/good_circuit_icon_32.png");
    register_catalog_item("circuit_advanced", "circuit_advanced", 64, kComponents,
                          "circuits/advanced_circuit_icon_32.png");
    register_catalog_item("coal_block", "coal_block", 64, kComponents,
                          "components/coal_block_icon_32.png");
    register_catalog_item("coke_brick", "coke_brick", 64, kComponents,
                          "components/coke_brick_icon_32.png");
    register_catalog_item("firebrick", "firebrick", 64, kComponents,
                          "components/firebrick_icon_32.png");
    register_catalog_item("stone_plate", "stone_plate", 64, kComponents,
                          "components/stone_plate_icon_32.png");
    register_catalog_item("wood_plate", "wood_plate", 64, kComponents,
                          "components/wood_plate_icon_32.png");
    register_catalog_item("blank_pattern", "blank_pattern", 64, kComponents,
                          "components/blank_pattern_icon_32.png");

    // Placeable and P7 machine item definitions.
    register_catalog_item("workbench", "workbench", 64, kPlaceables,
                          "placeables/workbench_icon_32.png");
    register_catalog_item("furnace", "item.furnace", 1, kPlaceables,
                          "placeables/stone_furnace_icon_32.png");
    register_catalog_item("pit_kiln", "item.pit_kiln", 1, kPlaceables, "");
    register_catalog_item("charcoal_pit", "item.charcoal_pit", 1, kPlaceables, "");
    register_catalog_item("bloomery", "item.bloomery", 1, kPlaceables, "");
    register_catalog_item("campfire", "campfire", 1, kPlaceables,
                          "placeables/campfire_icon_32.png");
    register_catalog_item("ladder", "ladder", 64, kPlaceables,
                          "placeables/ladder_icon_32.png");
    register_catalog_item("fence", "fence", 64, kPlaceables,
                          "placeables/fence_icon_32.png");
    register_catalog_item("station_blueprint", "station_blueprint", 1, kPlaceables,
                          "components/station_blueprint_icon_32.png");
    register_catalog_item("sfm_manager", "sfm.block.manager", 64, kPlaceables,
                          "components/sfm_manager_icon_32.png");
    register_catalog_item("ae_controller", "ae.block.controller", 64, kPlaceables, "");
    register_catalog_item("ae_cable", "ae.block.cable", 64, kPlaceables, "");
    register_catalog_item("ae_channel_provider", "ae.block.channel_provider", 64, kPlaceables, "");
    register_catalog_item("ae_drive_1k", "ae.block.drive_1k", 64, kPlaceables, "");
    register_catalog_item("ae_storage_bus", "ae.block.storage_bus", 64, kPlaceables, "");
    register_catalog_item("ae_interface", "ae.block.interface", 64, kPlaceables, "");
    register_catalog_item("ae_terminal", "ae.block.terminal", 64, kPlaceables, "");
    register_catalog_item("sfm_cable", "sfm.block.cable", 64, kPlaceables,
                          "components/sfm_cable_icon_32.png");
    register_tinted_catalog_item("iron_ore", "item.iron_ore", 64, kResources,
                                 "material_sets/generic/crushed_base_32.png", 0xc8b0a0);

    // Primitive resources, pottery, and metallurgy.
    register_catalog_item("clay_ball", "item.clay_ball", 64, kResources,
                          "tfc/clay_ball_icon_32.png");
    register_catalog_item("straw", "item.straw", 64, kResources,
                          "tfc/straw_icon_32.png");
    register_catalog_item("charcoal", "item.charcoal", 64, kResources,
                          "tfc/charcoal_icon_32.png");
    register_tinted_catalog_item("coal_dust", "item.coal_dust", 64, kResources,
                                 "material_sets/generic/dust_base_32.png", 0x1a1a1a);
    register_catalog_item("flint_and_steel", "item.flint_and_steel", 1, kResources,
                          "tfc/flint_and_steel_icon_32.png");
    register_catalog_item("unfired_bowl", "item.unfired_bowl", 16, kResources,
                          "tfc/unfired_bowl_icon_32.png");
    register_catalog_item("unfired_jug", "item.unfired_jug", 16, kResources,
                          "tfc/unfired_jug_icon_32.png");
    register_catalog_item("unfired_crucible", "item.unfired_crucible", 16, kResources,
                          "tfc/unfired_crucible_icon_32.png");
    register_catalog_item("unfired_brick", "item.unfired_brick", 64, kResources,
                          "tfc/unfired_brick_icon_32.png");
    register_catalog_item("fired_bowl", "item.fired_bowl", 16, kResources,
                          "tfc/fired_bowl_icon_32.png");
    register_catalog_item("fired_jug", "item.fired_jug", 16, kResources,
                          "tfc/fired_jug_icon_32.png");
    register_catalog_item("fired_crucible", "item.fired_crucible", 16, kResources,
                          "tfc/fired_crucible_icon_32.png");
    register_catalog_item("refractory_brick", "item.refractory_brick", 64, kResources,
                          "tfc/refractory_brick_icon_32.png");
    register_catalog_item("iron_bloom", "item.iron_bloom", 16, kResources,
                          "tfc/iron_bloom_icon_32.png");
    register_catalog_tool("hammer", "item.hammer", "tools/hammer_icon_32.png",
                          kToolNone, 0, "iron", 1.0f, 200, 1.0f);
    snt_add_item_tool_tag("hammer", "hammer");
    register_catalog_item("bellows", "item.bellows", 1, kResources,
                          "tfc/bellows_icon_32.png");
    register_catalog_item("anvil", "item.anvil", 1, kPlaceables,
                          "placeables/anvil_icon_32.png");

    // Tree species resources.
    register_catalog_item("log.oak", "log.oak", 64, kMaterials,
                          "trees/log_oak_icon_64.png");
    register_catalog_item("plank.oak", "plank.oak", 64, kMaterials,
                          "trees/plank_oak_icon_64.png");
    register_catalog_item("sapling.oak", "sapling.oak", 64, kMaterials,
                          "trees/sapling_oak_icon_64.png");
    register_catalog_item("log.birch", "log.birch", 64, kMaterials,
                          "trees/log_birch_icon_64.png");
    register_catalog_item("plank.birch", "plank.birch", 64, kMaterials,
                          "trees/plank_birch_icon_64.png");
    register_catalog_item("sapling.birch", "sapling.birch", 64, kMaterials,
                          "trees/sapling_birch_icon_64.png");
    register_catalog_item("log.spruce", "log.spruce", 64, kMaterials,
                          "trees/log_spruce_icon_64.png");
    register_catalog_item("plank.spruce", "plank.spruce", 64, kMaterials,
                          "trees/plank_spruce_icon_64.png");
    register_catalog_item("sapling.spruce", "sapling.spruce", 64, kMaterials,
                          "trees/sapling_spruce_icon_64.png");
    register_catalog_item("log.acacia", "log.acacia", 64, kMaterials,
                          "trees/log_acacia_icon_64.png");
    register_catalog_item("plank.acacia", "plank.acacia", 64, kMaterials,
                          "trees/plank_acacia_icon_64.png");
    register_catalog_item("sapling.acacia", "sapling.acacia", 64, kMaterials,
                          "trees/sapling_acacia_icon_64.png");
    register_catalog_item("log.maple", "log.maple", 64, kMaterials,
                          "trees/log_maple_icon_64.png");
    register_catalog_item("plank.maple", "plank.maple", 64, kMaterials,
                          "trees/plank_maple_icon_64.png");
    register_catalog_item("sapling.maple", "sapling.maple", 64, kMaterials,
                          "trees/sapling_maple_icon_64.png");
    register_catalog_item("log.sequoia", "log.sequoia", 64, kMaterials,
                          "trees/log_sequoia_icon_64.png");
    register_catalog_item("plank.sequoia", "plank.sequoia", 64, kMaterials,
                          "trees/plank_sequoia_icon_64.png");
    register_catalog_item("sapling.sequoia", "sapling.sequoia", 64, kMaterials,
                          "trees/sapling_sequoia_icon_64.png");
    register_catalog_item("log.cherry", "log.cherry", 64, kMaterials,
                          "trees/log_cherry_icon_64.png");
    register_catalog_item("plank.cherry", "plank.cherry", 64, kMaterials,
                          "trees/plank_cherry_icon_64.png");
    register_catalog_item("sapling.cherry", "sapling.cherry", 64, kMaterials,
                          "trees/sapling_cherry_icon_64.png");
    register_catalog_item("fruit.cherry", "fruit.cherry", 64, kMaterials,
                          "trees/fruit_cherry_icon_64.png");
    register_catalog_item("log.olive", "log.olive", 64, kMaterials,
                          "trees/log_olive_icon_64.png");
    register_catalog_item("plank.olive", "plank.olive", 64, kMaterials,
                          "trees/plank_olive_icon_64.png");
    register_catalog_item("sapling.olive", "sapling.olive", 64, kMaterials,
                          "trees/sapling_olive_icon_64.png");
    register_catalog_item("fruit.olive", "fruit.olive", 64, kMaterials,
                          "trees/fruit_olive_icon_64.png");

    // Source-law creature drops retain their canonical namespaced keys.
    register_catalog_item("snt:glow_deer_antler", "snt:glow_deer_antler", 64, kResources,
                          "source_law/glow_deer_antler_icon_32.png");
    register_catalog_item("snt:purifying_pollen", "snt:purifying_pollen", 64, kResources,
                          "source_law/purifying_pollen_icon_32.png");
    register_catalog_item("snt:rock_lizard_scale", "snt:rock_lizard_scale", 64, kResources,
                          "source_law/rock_lizard_scale_icon_32.png");
    register_catalog_item("snt:crystallized_bone_powder", "snt:crystallized_bone_powder", 64, kResources,
                          "source_law/crystallized_bone_powder_icon_32.png");
    register_catalog_item("snt:thunderbird_feather", "snt:thunderbird_feather", 64, kResources,
                          "source_law/thunderbird_feather_icon_32.png");
    register_catalog_item("snt:magnetic_crystal_shard", "snt:magnetic_crystal_shard", 64, kResources,
                          "source_law/magnetic_crystal_shard_icon_32.png");
    register_catalog_item("snt:sea_serpent_scale", "snt:sea_serpent_scale", 64, kResources,
                          "source_law/sea_serpent_scale_icon_32.png");
    register_catalog_item("snt:tidal_gland", "snt:tidal_gland", 64, kResources,
                          "source_law/tidal_gland_icon_32.png");
    register_catalog_item("snt:blazing_core", "snt:blazing_core", 64, kResources,
                          "source_law/blazing_core_icon_32.png");
    register_catalog_item("snt:molten_blood_sample", "snt:molten_blood_sample", 64, kResources,
                          "source_law/molten_blood_sample_icon_32.png");
    register_catalog_item("snt:aether_fragment", "snt:aether_fragment", 64, kResources,
                          "source_law/aether_fragment_icon_32.png");
    register_catalog_item("snt:blueprint_shard", "snt:blueprint_shard", 64, kResources,
                          "source_law/blueprint_shard_icon_32.png");
    register_catalog_item("snt:aberrant_organ", "snt:aberrant_organ", 64, kResources,
                          "source_law/aberrant_organ_icon_32.png");
    register_catalog_item("snt:polluted_source_essence", "snt:polluted_source_essence", 64, kResources,
                          "source_law/polluted_source_essence_icon_32.png");

    // Crop seed, crop, and processed-food items.
    register_catalog_item("seed.wheat", "item.wheat_seed", 64, kFood,
                          "crops/seed_wheat_icon_32.png");
    register_catalog_item("crop.wheat", "item.wheat_crop", 64, kFood,
                          "crops/crop_wheat_icon_32.png");
    register_catalog_item("seed.carrot", "item.carrot_seed", 64, kFood,
                          "crops/seed_carrot_icon_32.png");
    register_catalog_item("crop.carrot", "item.carrot_crop", 64, kFood,
                          "crops/crop_carrot_icon_32.png");
    register_catalog_item("seed.potato", "item.potato_seed", 64, kFood,
                          "crops/seed_potato_icon_32.png");
    register_catalog_item("crop.potato", "item.potato_crop", 64, kFood,
                          "crops/crop_potato_icon_32.png");
    register_catalog_item("seed.cotton", "item.cotton_seed", 64, kFood,
                          "crops/seed_cotton_icon_32.png");
    register_catalog_item("crop.cotton", "item.cotton_crop", 64, kFood,
                          "crops/crop_cotton_icon_32.png");
    register_catalog_item("seed.herb", "item.herb_seed", 64, kFood,
                          "crops/seed_herb_icon_32.png");
    register_catalog_item("crop.herb", "item.herb_crop", 64, kFood,
                          "crops/crop_herb_icon_32.png");
    register_catalog_item("seed.pumpkin", "item.pumpkin_seed", 64, kFood,
                          "crops/seed_pumpkin_icon_32.png");
    register_catalog_item("crop.pumpkin", "item.pumpkin_crop", 64, kFood,
                          "crops/crop_pumpkin_icon_32.png");
    register_catalog_item("bone_meal", "item.bone_meal", 64, kFood,
                          "crops/bone_meal_icon_32.png");
    register_catalog_item("flour", "item.flour", 64, kFood,
                          "crops/flour_icon_32.png");
    register_catalog_item("bread", "item.bread", 64, kFood,
                          "crops/bread_icon_32.png");
    register_catalog_item("fiber.cotton", "item.cotton_fiber", 64, kFood,
                          "crops/fiber_cotton_icon_32.png");
    register_catalog_item("cloth", "item.cloth", 64, kFood,
                          "crops/cloth_icon_32.png");

    // Creature food items use one canonical item key each.
    register_catalog_item("meat.raw.glow_deer", "item.meat.raw.glow_deer", 64, kFood,
                          "food/meat_raw_glow_deer_icon_32.png");
    register_catalog_item("meat.cooked.glow_deer", "item.meat.cooked.glow_deer", 64, kFood,
                          "food/meat_cooked_glow_deer_icon_32.png");
    register_catalog_item("meat.raw.rock_lizard", "item.meat.raw.rock_lizard", 64, kFood,
                          "food/meat_raw_rock_lizard_icon_32.png");
    register_catalog_item("meat.cooked.rock_lizard", "item.meat.cooked.rock_lizard", 64, kFood,
                          "food/meat_cooked_rock_lizard_icon_32.png");
    register_catalog_item("meat.raw.thunderbird", "item.meat.raw.thunderbird", 64, kFood,
                          "food/meat_raw_thunderbird_icon_32.png");
    register_catalog_item("meat.cooked.thunderbird", "item.meat.cooked.thunderbird", 64, kFood,
                          "food/meat_cooked_thunderbird_icon_32.png");
    register_catalog_item("meat.raw.sea_serpent", "item.meat.raw.sea_serpent", 64, kFood,
                          "food/meat_raw_sea_serpent_icon_32.png");
    register_catalog_item("meat.cooked.sea_serpent", "item.meat.cooked.sea_serpent", 64, kFood,
                          "food/meat_cooked_sea_serpent_icon_32.png");
    register_catalog_item("meat.raw.blaze_beast", "item.meat.raw.blaze_beast", 64, kFood,
                          "food/meat_raw_blaze_beast_icon_32.png");
    register_catalog_item("meat.cooked.blaze_beast", "item.meat.cooked.blaze_beast", 64, kFood,
                          "food/meat_cooked_blaze_beast_icon_32.png");

    // Fluid identity is a stable content id resolved to a ResourceKey at the
    // runtime snapshot boundary. There are no
    // authored numeric IDs: the immutable runtime snapshot assigns compact
    // IDs after this complete item-and-fluid catalog commits.
    snt_register_fluid("water", "fluid.water", "H2O", 300, false,
                       "steam", 373, "", 0);
    snt_register_fluid("lava", "fluid.lava", "?", 1500, false,
                       "", 0, "", 0);
    snt_register_fluid("steam", "fluid.steam", "H2O", 400, true,
                       "", 0, "water", 373);

    snt_register_fluid("oil", "fluid.oil", "?", 300, false,
                       "", 0, "", 0);
    snt_register_fluid("oil_heavy", "fluid.oil_heavy", "?", 350, false,
                       "", 0, "", 0);
    snt_register_fluid("oil_light", "fluid.oil_light", "?", 250, false,
                       "", 0, "", 0);

    snt_register_fluid("fuel_diesel", "fluid.fuel_diesel", "?", 250, false,
                       "", 0, "", 0);
    snt_register_fluid("fuel_rocket", "fluid.fuel_rocket", "?", 200, false,
                       "", 0, "", 0);
    snt_register_fluid("ethanol", "fluid.ethanol", "C2H5OH", 300, false,
                       "", 0, "", 0);

    snt_register_fluid("sulfuric_acid", "fluid.sulfuric_acid", "H2SO4", 300, false,
                       "", 0, "", 0);
    snt_register_fluid("hydrochloric_acid", "fluid.hydrochloric_acid", "HCl", 300, false,
                       "", 0, "", 0);
    snt_register_fluid("nitric_acid", "fluid.nitric_acid", "HNO3", 300, false,
                       "", 0, "", 0);
    snt_register_fluid("hydrofluoric_acid", "fluid.hydrofluoric_acid", "HF", 300, false,
                       "", 0, "", 0);
    snt_register_fluid("aqua_regia", "fluid.aqua_regia", "HNO3+3HCl", 300, false,
                       "", 0, "", 0);

    snt_register_fluid("creosote", "fluid.creosote", "?", 400, false,
                       "", 0, "", 0);
    snt_register_fluid("lubricant", "fluid.lubricant", "?", 300, false,
                       "", 0, "", 0);
    snt_register_fluid("glue", "fluid.glue", "?", 300, false,
                       "", 0, "", 0);
    snt_register_fluid("biomass", "fluid.biomass", "?", 300, false,
                       "", 0, "", 0);

    snt_register_fluid("oxygen", "fluid.oxygen", "O2", 90, true,
                       "", 0, "", 0);
    snt_register_fluid("hydrogen", "fluid.hydrogen", "H2", 20, true,
                       "", 0, "", 0);
    snt_register_fluid("nitrogen", "fluid.nitrogen", "N2", 77, true,
                       "", 0, "", 0);
    snt_register_fluid("natural_gas", "fluid.natural_gas", "CH4", 111, true,
                       "", 0, "", 0);

    snt_register_fluid("molten_iron", "fluid.molten_iron", "Fe", 1811, false,
                       "", 0, "", 0);
    snt_register_fluid("molten_gold", "fluid.molten_gold", "Au", 1337, false,
                       "", 0, "", 0);
    snt_register_fluid("molten_copper", "fluid.molten_copper", "Cu", 1358, false,
                       "", 0, "", 0);
    snt_register_fluid("molten_tin", "fluid.molten_tin", "Sn", 505, false,
                       "", 0, "", 0);
    snt_register_fluid("molten_lead", "fluid.molten_lead", "Pb", 601, false,
                       "", 0, "", 0);

    snt_register_fluid("mercury", "fluid.mercury", "Hg", 234, false,
                       "", 0, "", 0);
    snt_register_fluid("distilled_water", "fluid.distilled_water", "H2O", 300, false,
                       "", 0, "", 0);

    snt_log("Registered migrated resource catalog: 157 authored items, 29 fluids");
}
