// World-generation catalog authored in AngelScript.
//
// This module is reloaded atomically by GameContentReloadService. A running
// world keeps its frozen snapshot; the next server/world creation builds a
// new snapshot from the latest committed implementation of this function.

void snt_register() {}

void register_terrain_materials() {
    snt_register_worldgen_material("snt:acacia_leaves", "terrain.acacia_leaves", 9, 0.15f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:acacia_sapling", "terrain.acacia_sapling", 8, 0.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:acacia_sapling", "sapling.acacia", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:acacia_wood", "terrain.acacia_wood", 10, 0.9f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:acacia_wood", "log.acacia", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:air", "terrain.air", 0, 0.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:anorthosite_rock", "terrain.anorthosite", 138, 1.4f, "pickaxe", 1, 0.2f, 5, "snt:anorthosite");
    snt_add_worldgen_material_drop("snt:anorthosite_rock", "dust.anorthosite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:anvil", "terrain.anvil", 10, 4.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_register_worldgen_material("snt:basalt_rock", "terrain.basalt", 138, 2.0f, "pickaxe", 1, 0.25f, 5, "snt:basalt");
    snt_add_worldgen_material_drop("snt:basalt_rock", "dust.basalt", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:birch_leaves", "terrain.birch_leaves", 9, 0.15f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:birch_sapling", "terrain.birch_sapling", 8, 0.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:birch_sapling", "sapling.birch", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:birch_wood", "terrain.birch_wood", 10, 0.8f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:birch_wood", "log.birch", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:bloomery", "terrain.bloomery", 10, 3.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:bloomery", "refractory_brick", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:carrot_growing", "terrain.carrot_growing", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:carrot_growing", "seed.carrot", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:carrot_mature", "terrain.carrot_mature", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:carrot_mature", "crop.carrot", 1, 1, 1, 1.0f);
    snt_add_worldgen_material_drop("snt:carrot_mature", "seed.carrot", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:carrot_seed", "terrain.carrot_seed", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:carrot_seed", "seed.carrot", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:carrot_sprout", "terrain.carrot_sprout", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:carrot_sprout", "seed.carrot", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:charcoal", "terrain.charcoal", 10, 0.5f, "pickaxe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:charcoal", "charcoal", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:cherry_leaves", "terrain.cherry_leaves", 9, 0.15f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:cherry_sapling", "terrain.cherry_sapling", 8, 0.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:cherry_sapling", "sapling.cherry", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:cherry_wood", "terrain.cherry_wood", 10, 0.7f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:cherry_wood", "log.cherry", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:clay", "terrain.clay", 9, 0.4f, "shovel", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:clay", "clay_ball", 1, 1, 3, 1.0f);
    snt_register_worldgen_material("snt:core_barrier", "terrain.core_barrier", 34, -1.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:cotton_growing", "terrain.cotton_growing", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:cotton_growing", "seed.cotton", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:cotton_mature", "terrain.cotton_mature", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:cotton_mature", "crop.cotton", 1, 1, 1, 1.0f);
    snt_add_worldgen_material_drop("snt:cotton_mature", "seed.cotton", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:cotton_seed", "terrain.cotton_seed", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:cotton_seed", "seed.cotton", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:cotton_sprout", "terrain.cotton_sprout", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:cotton_sprout", "seed.cotton", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:deepstone", "terrain.deepstone", 138, 10.0f, "pickaxe", 3, 0.5f, 5, "snt:deeprock");
    snt_add_worldgen_material_drop("snt:deepstone", "dust.stone", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:dirt", "terrain.dirt", 9, 0.5f, "shovel", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:dirt", "tiny_dust.stone", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:farmland", "terrain.farmland", 11, 0.5f, "shovel", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:fence", "terrain.fence", 10, 1.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:fence", "fence", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:granite_rock", "terrain.granite", 138, 1.5f, "pickaxe", 1, 0.3f, 5, "snt:granite");
    snt_add_worldgen_material_drop("snt:granite_rock", "dust.granite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:herb_growing", "terrain.herb_growing", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:herb_growing", "seed.herb", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:herb_mature", "terrain.herb_mature", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:herb_mature", "crop.herb", 1, 1, 1, 1.0f);
    snt_add_worldgen_material_drop("snt:herb_mature", "seed.herb", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:herb_seed", "terrain.herb_seed", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:herb_seed", "seed.herb", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:herb_sprout", "terrain.herb_sprout", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:herb_sprout", "seed.herb", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ice", "terrain.ice", 11, 0.6f, "pickaxe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:komatiite_rock", "terrain.komatiite", 138, 2.5f, "pickaxe", 2, 0.35f, 5, "snt:komatiite");
    snt_add_worldgen_material_drop("snt:komatiite_rock", "dust.komatiite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ladder", "terrain.ladder", 24, 0.5f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ladder", "ladder", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:lava", "terrain.lava", 4, 100.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:leaves", "terrain.leaves", 9, 0.2f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:log_pile", "terrain.log_pile", 10, 0.6f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:maple_leaves", "terrain.maple_leaves", 9, 0.2f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:maple_sapling", "terrain.maple_sapling", 8, 0.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:maple_sapling", "sapling.maple", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:maple_wood", "terrain.maple_wood", 10, 1.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:maple_wood", "log.maple", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:marble_rock", "terrain.marble", 138, 1.3f, "pickaxe", 1, 0.2f, 5, "snt:marble");
    snt_add_worldgen_material_drop("snt:marble_rock", "dust.marble", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:oak_leaves", "terrain.oak_leaves", 9, 0.2f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:oak_sapling", "terrain.oak_sapling", 8, 0.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:oak_sapling", "sapling.oak", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:oak_wood", "terrain.oak_wood", 10, 1.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:oak_wood", "log.oak", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:olive_leaves", "terrain.olive_leaves", 9, 0.2f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:olive_sapling", "terrain.olive_sapling", 8, 0.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:olive_sapling", "sapling.olive", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:olive_wood", "terrain.olive_wood", 10, 1.1f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:olive_wood", "log.olive", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_antimony", "terrain.antimony_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_antimony", "crushed.stibnite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_arsenic", "terrain.arsenic_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_arsenic", "crushed.arsenopyrite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_barium", "terrain.barium_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_barium", "crushed.barite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_bauxite", "terrain.bauxite_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_bauxite", "crushed.bauxite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_beryllium", "terrain.beryllium_ore", 10, 2.5f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_beryllium", "crushed.bertrandite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_bismuth", "terrain.bismuth_ore", 10, 2.5f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_bismuth", "crushed.bismuthinite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_boron", "terrain.boron_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_boron", "crushed.kernite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_bromine", "terrain.bromine_ore", 10, 1.2f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_bromine", "crushed.bromargyrite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_cadmium", "terrain.cadmium_ore", 10, 1.8f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_cadmium", "crushed.greenockite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_calcium", "terrain.calcium_ore", 10, 1.5f, "pickaxe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_calcium", "crushed.calcite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_cassiterite", "terrain.cassiterite_ore", 10, 2.5f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_cassiterite", "crushed.cassiterite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_cesium", "terrain.cesium_ore", 10, 1.5f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_cesium", "crushed.pollucite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_chalcopyrite", "terrain.chalcopyrite_ore", 10, 2.2f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_chalcopyrite", "crushed.chalcopyrite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_chromium", "terrain.chromium_ore", 10, 3.5f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_chromium", "crushed.chromite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_cinnabar", "terrain.cinnabar_ore", 10, 1.8f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_cinnabar", "dust.cinnabar", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_coal", "terrain.coal_ore", 10, 1.8f, "pickaxe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_coal", "gem.coal", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_cobalt", "terrain.cobalt_ore", 10, 3.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_cobalt", "crushed.cobaltite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_copper", "terrain.copper_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_copper", "crushed.malachite", 1, 1, 2, 1.0f);
    snt_register_worldgen_material("snt:ore_diamond", "terrain.diamond_ore", 10, 5.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_diamond", "gem.diamond", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_emerald", "terrain.emerald_ore", 10, 4.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_emerald", "gem.emerald", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_fluorite", "terrain.fluorite_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_fluorite", "dust.fluorite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_galena", "terrain.galena_ore", 10, 2.3f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_galena", "crushed.galena", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_gallium", "terrain.gallium_ore", 10, 2.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_gallium", "crushed.gallite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_germanium", "terrain.germanium_ore", 10, 2.5f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_germanium", "crushed.germanite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_gold", "terrain.gold_ore", 10, 3.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_gold", "crushed.gold", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_graphite", "terrain.graphite_ore", 10, 1.8f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_graphite", "dust.graphite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_hafnium", "terrain.hafnium_ore", 10, 3.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_hafnium", "crushed.baddeleyite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_ilmenite", "terrain.ilmenite_ore", 10, 3.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_ilmenite", "crushed.ilmenite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_indium", "terrain.indium_ore", 10, 2.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_indium", "crushed.roquesite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_iodine", "terrain.iodine_ore", 10, 1.2f, "pickaxe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_iodine", "crushed.iodargyrite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_iridium", "terrain.iridium_ore", 10, 5.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_iridium", "crushed.iridium_oxide", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_iron", "terrain.iron_ore", 10, 2.5f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_iron", "crushed.hematite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_lead", "terrain.lead_ore", 10, 2.2f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_lead", "crushed.galena", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_lithium", "terrain.lithium_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_lithium", "crushed.spodumene", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_magnesium", "terrain.magnesium_ore", 10, 1.8f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_magnesium", "crushed.magnesite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_magnetite", "terrain.magnetite_ore", 10, 3.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_magnetite", "crushed.magnetite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_manganese", "terrain.manganese_ore", 10, 2.5f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_manganese", "crushed.pyrolusite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_molybdenum", "terrain.molybdenum_ore", 10, 3.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_molybdenum", "crushed.molybdenite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_nickel", "terrain.nickel_ore", 10, 2.8f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_nickel", "crushed.pentlandite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_niobium", "terrain.niobium_ore", 10, 3.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_niobium", "crushed.columbite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_osmium", "terrain.osmium_ore", 10, 5.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_osmium", "crushed.osmiridium", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_palladium", "terrain.palladium_ore", 10, 4.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_palladium", "crushed.stibiopalladinite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_pentlandite", "terrain.pentlandite_ore", 10, 2.8f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_pentlandite", "crushed.pentlandite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_phosphorus", "terrain.phosphorus_ore", 10, 1.5f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_phosphorus", "crushed.apatite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_platinum", "terrain.platinum_ore", 10, 5.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_platinum", "crushed.sperrylite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_potassium", "terrain.potassium_ore", 10, 1.2f, "pickaxe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_potassium", "crushed.sylvite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_pyrite", "terrain.pyrite_ore", 10, 2.5f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_pyrite", "crushed.pyrite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_rare_earth", "terrain.rare_earth_ore", 10, 3.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_rare_earth", "crushed.monazite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_rhenium", "terrain.rhenium_ore", 10, 4.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_rhenium", "crushed.rheniite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_rhodium", "terrain.rhodium_ore", 10, 4.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_rhodium", "crushed.rhodium_oxide", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_rubidium", "terrain.rubidium_ore", 10, 1.5f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_rubidium", "crushed.lepidolite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_ruby", "terrain.ruby_ore", 10, 4.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_ruby", "gem.ruby", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_ruthenium", "terrain.ruthenium_ore", 10, 4.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_ruthenium", "crushed.laurite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_salt", "terrain.salt_ore", 10, 1.2f, "pickaxe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_salt", "dust.salt", 1, 1, 3, 1.0f);
    snt_register_worldgen_material("snt:ore_sapphire", "terrain.sapphire_ore", 10, 4.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_sapphire", "gem.sapphire", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_scandium", "terrain.scandium_ore", 10, 3.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_scandium", "crushed.thortveitite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_selenium", "terrain.selenium_ore", 10, 1.8f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_selenium", "crushed.clausthalite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_silver", "terrain.silver_ore", 10, 2.8f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_silver", "crushed.silver", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_sphalerite", "terrain.sphalerite_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_sphalerite", "crushed.sphalerite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_strontium", "terrain.strontium_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_strontium", "crushed.celestine", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_sulfur", "terrain.sulfur_ore", 10, 1.5f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_sulfur", "dust.sulfur", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_tantalum", "terrain.tantalum_ore", 10, 4.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_tantalum", "crushed.tantalite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_tellurium", "terrain.tellurium_ore", 10, 2.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_tellurium", "crushed.calaverite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_thallium", "terrain.thallium_ore", 10, 2.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_thallium", "crushed.crookesite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_thorium", "terrain.thorium_ore", 10, 4.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_thorium", "crushed.thorite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_tin", "terrain.tin_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_tin", "crushed.cassiterite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_titanium", "terrain.titanium_ore", 10, 4.5f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_titanium", "crushed.rutile", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_tungsten", "terrain.tungsten_ore", 10, 4.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_tungsten", "crushed.wolframite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_uranium", "terrain.uranium_ore", 10, 5.0f, "pickaxe", 3, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_uranium", "crushed.uraninite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_vanadium", "terrain.vanadium_ore", 10, 3.0f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_vanadium", "crushed.patronite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_yttrium", "terrain.yttrium_ore", 10, 2.5f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_yttrium", "crushed.xenotime", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_zinc", "terrain.zinc_ore", 10, 2.0f, "pickaxe", 1, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_zinc", "crushed.sphalerite", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:ore_zirconium", "terrain.zirconium_ore", 10, 3.5f, "pickaxe", 2, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:ore_zirconium", "crushed.zircon", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:pit_kiln", "terrain.pit_kiln", 10, 0.8f, "pickaxe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:potato_growing", "terrain.potato_growing", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:potato_growing", "seed.potato", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:potato_mature", "terrain.potato_mature", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:potato_mature", "crop.potato", 1, 1, 1, 1.0f);
    snt_add_worldgen_material_drop("snt:potato_mature", "seed.potato", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:potato_seed", "terrain.potato_seed", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:potato_seed", "seed.potato", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:potato_sprout", "terrain.potato_sprout", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:potato_sprout", "seed.potato", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:pumpkin_growing", "terrain.pumpkin_growing", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:pumpkin_growing", "seed.pumpkin", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:pumpkin_mature", "terrain.pumpkin_mature", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:pumpkin_mature", "crop.pumpkin", 1, 1, 1, 1.0f);
    snt_add_worldgen_material_drop("snt:pumpkin_mature", "seed.pumpkin", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:pumpkin_seed", "terrain.pumpkin_seed", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:pumpkin_seed", "seed.pumpkin", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:pumpkin_sprout", "terrain.pumpkin_sprout", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:pumpkin_sprout", "seed.pumpkin", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:regolith_rock", "terrain.regolith", 74, 0.6f, "shovel", 0, 0.1f, 5, "snt:regolith");
    snt_add_worldgen_material_drop("snt:regolith_rock", "dust.regolith", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:sand", "terrain.sand", 73, 0.45f, "shovel", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:sand", "tiny_dust.stone", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:sandstone_rock", "terrain.sandstone", 74, 0.8f, "pickaxe", 0, 0.15f, 5, "snt:sandstone");
    snt_add_worldgen_material_drop("snt:sandstone_rock", "dust.sandstone", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:sequoia_leaves", "terrain.sequoia_leaves", 9, 0.2f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:sequoia_sapling", "terrain.sequoia_sapling", 8, 0.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:sequoia_sapling", "sapling.sequoia", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:sequoia_wood", "terrain.sequoia_wood", 10, 1.2f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:sequoia_wood", "log.sequoia", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:shale_rock", "terrain.shale", 138, 1.0f, "pickaxe", 1, 0.4f, 5, "snt:shale");
    snt_add_worldgen_material_drop("snt:shale_rock", "dust.shale", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:snow", "terrain.snow", 9, 0.2f, "shovel", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:spruce_leaves", "terrain.spruce_leaves", 9, 0.2f, "axe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:spruce_sapling", "terrain.spruce_sapling", 8, 0.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:spruce_sapling", "sapling.spruce", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:spruce_wood", "terrain.spruce_wood", 10, 1.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:spruce_wood", "log.spruce", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:stone", "terrain.stone", 138, 1.5f, "pickaxe", 1, 0.3f, 5, "snt:granite");
    snt_add_worldgen_material_drop("snt:stone", "dust.stone", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:straw", "terrain.straw", 9, 0.1f, "hoe", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:water", "terrain.water", 4, 100.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:wheat_growing", "terrain.wheat_growing", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:wheat_growing", "seed.wheat", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:wheat_mature", "terrain.wheat_mature", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:wheat_mature", "crop.wheat", 1, 1, 1, 1.0f);
    snt_add_worldgen_material_drop("snt:wheat_mature", "seed.wheat", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:wheat_seed", "terrain.wheat_seed", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:wheat_seed", "seed.wheat", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:wheat_sprout", "terrain.wheat_sprout", 9, 0.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:wheat_sprout", "seed.wheat", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:wood", "terrain.wood", 10, 1.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:wood", "dust.wood", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:workbench", "terrain.workbench", 10, 1.0f, "axe", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:workbench", "workbench", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:runtime.bed", "terrain.runtime.bed", 11, 1.0f, "", 0, 0.3f, 5, "");
    snt_add_worldgen_material_drop("snt:runtime.bed", "bed", 1, 1, 1, 1.0f);
    snt_register_worldgen_material("snt:runtime.fire", "terrain.runtime.fire", 8, 0.1f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.machine.furnace", "terrain.runtime.machine.furnace", 11, 3.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.machine.pit_kiln", "terrain.runtime.machine.pit_kiln", 11, 0.8f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.machine.charcoal_pit", "terrain.runtime.machine.charcoal_pit", 11, 0.6f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.machine.bloomery", "terrain.runtime.machine.bloomery", 11, 3.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.machine.anvil", "terrain.runtime.machine.anvil", 11, 4.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.automation.sfm_manager", "terrain.runtime.automation.sfm_manager", 11, 2.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.automation.ae_controller", "terrain.runtime.automation.ae_controller", 11, 2.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.automation.ae_cable", "terrain.runtime.automation.ae_cable", 11, 0.5f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.automation.ae_channel_provider", "terrain.runtime.automation.ae_channel_provider", 11, 2.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.automation.ae_drive_1k", "terrain.runtime.automation.ae_drive_1k", 11, 2.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.automation.ae_storage_bus", "terrain.runtime.automation.ae_storage_bus", 11, 2.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.automation.ae_interface", "terrain.runtime.automation.ae_interface", 11, 2.0f, "", 0, 0.3f, 5, "");
    snt_register_worldgen_material("snt:runtime.automation.ae_terminal", "terrain.runtime.automation.ae_terminal", 11, 2.0f, "", 0, 0.3f, 5, "");
}

void register_terrain_roles() {
    snt_bind_worldgen_role("air", "snt:air");
    snt_bind_worldgen_role("stone", "snt:stone");
    snt_bind_worldgen_role("dirt", "snt:dirt");
    snt_bind_worldgen_role("sand", "snt:sand");
    snt_bind_worldgen_role("water", "snt:water");
    snt_bind_worldgen_role("lava", "snt:lava");
    snt_bind_worldgen_role("ore_iron", "snt:ore_iron");
    snt_bind_worldgen_role("ore_copper", "snt:ore_copper");
    snt_bind_worldgen_role("ore_coal", "snt:ore_coal");
    snt_bind_worldgen_role("wood", "snt:wood");
    snt_bind_worldgen_role("leaves", "snt:leaves");
    snt_bind_worldgen_role("deepstone", "snt:deepstone");
    snt_bind_worldgen_role("core_barrier", "snt:core_barrier");
    snt_bind_worldgen_role("snow", "snt:snow");
    snt_bind_worldgen_role("ice", "snt:ice");
    snt_bind_worldgen_runtime_material("ladder", "snt:ladder");
    snt_bind_worldgen_runtime_material("workbench", "snt:workbench");
    snt_bind_worldgen_runtime_material("fence", "snt:fence");
    snt_bind_worldgen_runtime_material("farmland", "snt:farmland");
    snt_bind_worldgen_runtime_material("bloomery", "snt:runtime.machine.bloomery");
}

void register_tree_species() {
    snt_register_worldgen_tree("oak", "tree.oak", -0.2f, 0.5f, 0.0f, 1.0f, 1.2f, 3, 5, 0, 2, "snt:oak_wood", "snt:oak_leaves", "snt:oak_sapling", false, 24000, 48000, false, "", -1);
    snt_set_worldgen_tree_colors("oak", 0.45f, 0.27f, 0.12f, 0.21f, 0.42f, 0.15f, 0.75f, 0.50f, 0.12f);
    snt_register_worldgen_tree("birch", "tree.birch", -0.6f, 0.2f, 0.1f, 1.0f, 0.8f, 5, 8, 3, 1, "snt:birch_wood", "snt:birch_leaves", "snt:birch_sapling", false, 20000, 40000, false, "", -1);
    snt_set_worldgen_tree_colors("birch", 0.80f, 0.78f, 0.70f, 0.25f, 0.55f, 0.18f, 0.85f, 0.75f, 0.15f);
    snt_register_worldgen_tree("spruce", "tree.spruce", -1.0f, -0.1f, 0.0f, 1.0f, 1.0f, 4, 7, 1, 2, "snt:spruce_wood", "snt:spruce_leaves", "snt:spruce_sapling", true, 30000, 60000, false, "", -1);
    snt_set_worldgen_tree_colors("spruce", 0.35f, 0.22f, 0.10f, 0.10f, 0.30f, 0.12f, 0.10f, 0.30f, 0.12f);
    snt_register_worldgen_tree("acacia", "tree.acacia", 0.5f, 1.0f, -0.5f, 0.5f, 0.7f, 3, 5, 2, 3, "snt:acacia_wood", "snt:acacia_leaves", "snt:acacia_sapling", false, 28000, 56000, false, "", -1);
    snt_set_worldgen_tree_colors("acacia", 0.55f, 0.35f, 0.15f, 0.30f, 0.55f, 0.12f, 0.70f, 0.55f, 0.10f);
    snt_register_worldgen_tree("maple", "tree.maple", -0.3f, 0.4f, 0.1f, 1.0f, 0.6f, 3, 6, 0, 2, "snt:maple_wood", "snt:maple_leaves", "snt:maple_sapling", false, 26000, 52000, false, "", -1);
    snt_set_worldgen_tree_colors("maple", 0.42f, 0.25f, 0.10f, 0.20f, 0.50f, 0.15f, 0.90f, 0.25f, 0.10f);
    snt_register_worldgen_tree("sequoia", "tree.sequoia", 0.1f, 0.6f, 0.3f, 1.0f, 0.4f, 7, 12, 1, 3, "snt:sequoia_wood", "snt:sequoia_leaves", "snt:sequoia_sapling", true, 40000, 80000, false, "", -1);
    snt_set_worldgen_tree_colors("sequoia", 0.40f, 0.23f, 0.10f, 0.12f, 0.32f, 0.10f, 0.12f, 0.32f, 0.10f);
    snt_register_worldgen_tree("cherry", "tree.cherry", -0.1f, 0.5f, 0.2f, 1.0f, 0.3f, 2, 4, 0, 2, "snt:cherry_wood", "snt:cherry_leaves", "snt:cherry_sapling", false, 22000, 44000, true, "fruit.cherry", 2);
    snt_set_worldgen_tree_colors("cherry", 0.50f, 0.28f, 0.22f, 0.70f, 0.35f, 0.50f, 0.80f, 0.30f, 0.25f);
    snt_register_worldgen_tree("olive", "tree.olive", 0.2f, 0.8f, -0.2f, 0.6f, 0.3f, 2, 4, 0, 2, "snt:olive_wood", "snt:olive_leaves", "snt:olive_sapling", true, 32000, 64000, true, "fruit.olive", 1);
    snt_set_worldgen_tree_colors("olive", 0.52f, 0.40f, 0.22f, 0.25f, 0.38f, 0.15f, 0.25f, 0.38f, 0.15f);
}

void register_crop_species() {
    snt_register_worldgen_crop("wheat", "crop.wheat", 0, -0.3f, 0.6f, -0.2f, 0.6f, 0, 1, 2, 3000, 6000, 9000, "seed.wheat", "crop.wheat", "seed.wheat", 1, 2, 1, false, 6000, "snt:wheat_seed", "snt:wheat_sprout", "snt:wheat_growing", "snt:wheat_mature");
    snt_set_worldgen_crop_environment("wheat", 0.7f, 0.7f, true, 1.0f, 0.85f, 0.75f, 0.25f);
    snt_register_worldgen_crop("carrot", "crop.carrot", 1, -0.2f, 0.7f, -0.1f, 0.7f, 0, 1, 2, 2500, 5000, 8000, "seed.carrot", "crop.carrot", "", 1, 3, 0, false, 6000, "snt:carrot_seed", "snt:carrot_sprout", "snt:carrot_growing", "snt:carrot_mature");
    snt_set_worldgen_crop_environment("carrot", 0.5f, 0.6f, true, 0.8f, 0.75f, 0.45f, 0.15f);
    snt_register_worldgen_crop("potato", "crop.potato", 1, -0.4f, 0.5f, -0.2f, 0.8f, 0, 1, 2, 3000, 5500, 8500, "seed.potato", "crop.potato", "seed.potato", 1, 3, 1, false, 6000, "snt:potato_seed", "snt:potato_sprout", "snt:potato_growing", "snt:potato_mature");
    snt_set_worldgen_crop_environment("potato", 0.6f, 0.5f, false, 0.5f, 0.55f, 0.45f, 0.20f);
    snt_register_worldgen_crop("cotton", "crop.cotton", 2, 0.2f, 0.8f, -0.1f, 0.5f, 1, 1, 2, 3500, 7000, 10000, "seed.cotton", "crop.cotton", "seed.cotton", 1, 2, 1, false, 6000, "snt:cotton_seed", "snt:cotton_sprout", "snt:cotton_growing", "snt:cotton_mature");
    snt_set_worldgen_crop_environment("cotton", 0.8f, 0.7f, false, 0.3f, 0.92f, 0.90f, 0.85f);
    snt_register_worldgen_crop("herb", "crop.herb", 3, -0.3f, 0.5f, 0.0f, 0.8f, -1, -1, -1, 2000, 4000, 6000, "seed.herb", "crop.herb", "seed.herb", 1, 2, 1, true, 5000, "snt:herb_seed", "snt:herb_sprout", "snt:herb_growing", "snt:herb_mature");
    snt_set_worldgen_crop_environment("herb", 0.4f, 0.5f, true, 1.2f, 0.40f, 0.55f, 0.25f);
    snt_register_worldgen_crop("pumpkin", "crop.pumpkin", 4, 0.3f, 0.9f, 0.0f, 0.6f, 1, 1, 2, 4000, 8000, 12000, "seed.pumpkin", "crop.pumpkin", "seed.pumpkin", 1, 2, 1, false, 6000, "snt:pumpkin_seed", "snt:pumpkin_sprout", "snt:pumpkin_growing", "snt:pumpkin_mature");
    snt_set_worldgen_crop_environment("pumpkin", 0.7f, 0.8f, false, 0.4f, 0.90f, 0.55f, 0.15f);
}

void snt_register_worldgen() {
    register_terrain_materials();
    register_terrain_roles();
    register_tree_species();
    register_crop_species();
    snt_register_worldgen_base_terrain_rule(
        "overworld", "surface_elevation", "snt:dirt", "snt:water", "snt:stone", "snt:air",
        0.02f, 4, 0.05f, 3, -0.25f, 0.30f, 0.55f, 0.04f, 4, 0.35f, 0.25f);
}
