class_name BuiltinRunes
extends RefCounted

# Built-in rune definitions, migrated from C++ RuneRegistry::register_builtin_runes().
# 8 elements × 4 tiers = 32 runes, generated by rule.

# RuneElement: FIRE=0, WATER=1, EARTH=2, AIR=3, LIGHT=4, DARK=5, ORDER=6, CHAOS=7
# RuneTier: COMMON=0, REFINED=1, SUPERIOR=2, LEGENDARY=3
# potency: COMMON=1, REFINED=2, SUPERIOR=3, LEGENDARY=5

const _ELEMENT_NAMES := [
	"fire", "water", "earth", "air", "light", "dark", "order", "chaos"
]
const _TIER_NAMES := ["common", "refined", "superior", "legendary"]
const _TIER_POTENCY := [1, 2, 3, 5]


# Register all built-in runes with the C++ RuneRegistry via GDRuneRegistry.
static func register_all() -> void:
	for element in range(8):
		for tier in range(4):
			var name := "%s_rune_%s" % [_ELEMENT_NAMES[element], _TIER_NAMES[tier]]
			GDRuneRegistry.register_rune({
				"name": name,
				"element": element,
				"tier": tier,
				"potency": _TIER_POTENCY[tier],
			})
