#pragma once

#include <algorithm>
#include <cstdint>

namespace science_and_theology {

// ============================================================
// PopulationCell — per-chunk ecosystem population density
// ============================================================
//
// Stores aggregate population densities for a single chunk.
// Lightweight data structure (~25 bytes) used by EcosystemSystem
// for Lotka-Volterra-style population dynamics.
//
// All density values are in [0, 1] range where:
//   0.0 = completely absent
//   1.0 = maximum carrying capacity
//
// PopulationCell is owned by EcosystemSystem (not ChunkData) to
// keep world data concerns separate from simulation concerns.
// See design decision Q1 (方案B) in ecosystem design doc.

struct PopulationCell {
    // Ground vegetation cover [0, 1].
    // Influenced by soil fertility, water, season, and herbivore grazing.
    float vegetation_density = 0.5f;

    // Herbivore (prey) population density [0, 1].
    // Influenced by vegetation availability and predator pressure.
    float herbivore_density = 0.3f;

    // Predator population density [0, 1].
    // Influenced by herbivore availability.
    float predator_density = 0.1f;

    // Soil nutrient level [0, 1].
    // Increased by decomposition of dead biomass.
    float soil_fertility = 0.5f;

    // Water availability for vegetation [0, 1].
    // Determined by biome base value and seasonal modifier.
    float water_availability = 0.5f;

    // Decomposing organic matter [0, 1].
    // Generated by animal death and vegetation decay;
    // consumed by decomposition into soil fertility.
    float dead_biomass = 0.0f;

    // Biome type index for parameter lookup in EcosystemParams.
    uint8_t biome_type = 0;

    // Clamp all density values to [0, 1].
    void clamp_all() {
        vegetation_density = std::clamp(vegetation_density, 0.0f, 1.0f);
        herbivore_density = std::clamp(herbivore_density, 0.0f, 1.0f);
        predator_density = std::clamp(predator_density, 0.0f, 1.0f);
        soil_fertility = std::clamp(soil_fertility, 0.0f, 1.0f);
        water_availability = std::clamp(water_availability, 0.0f, 1.0f);
        dead_biomass = std::clamp(dead_biomass, 0.0f, 1.0f);
    }
};

} // namespace science_and_theology
